-- Batch 10: altre spiegazioni mainstream, livello vario.

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché quando si piange di gioia si producono le stesse lacrime di quando si piange di tristezza?', 'Ragazzo', '👨', 'medio', 750, $$Le lacrime emotive (diverse da quelle prodotte per lubrificare l'occhio o per irritazione, come quelle della cipolla) hanno effettivamente una composizione chimica leggermente diversa, contenendo ormoni dello stress e endorfine, ma il meccanismo fisico che le produce è lo stesso indipendentemente dall'emozione scatenante: un'intensa attivazione del sistema nervoso autonomo, che può essere innescata sia da un dolore emotivo forte sia da una gioia travolgente o da un sollievo improvviso. Il cervello, di fronte a un'emozione che supera una certa soglia di intensità, attiva la stessa risposta fisiologica di pianto indipendentemente dalla sua natura positiva o negativa — è la situazione e il contesto (non le lacrime in sé) a dirci se qualcuno sta piangendo per dolore o per felicità.$$),

(NULL, 'Come funziona il sistema previdenziale (le pensioni) in Italia?', 'Adulto', '👤', 'medio', 950, $$Il sistema pensionistico italiano funziona principalmente a ripartizione: i contributi versati dai lavoratori attivi oggi finanziano immediatamente le pensioni di chi è già in pensione oggi (non vengono accantonati individualmente per ciascun lavoratore in un conto personale separato). Dal 1996 (riforma Dini) il calcolo è passato progressivamente dal metodo retributivo (basato sugli ultimi stipendi percepiti) al metodo contributivo (basato sui contributi effettivamente versati durante tutta la carriera lavorativa, rivalutati nel tempo). Questo sistema espone il paese a una sfida strutturale nota come rapporto di dipendenza demografica: quando il numero di pensionati cresce rispetto al numero di lavoratori attivi che versano contributi (a causa dell'invecchiamento della popolazione e della bassa natalità), l'equilibrio finanziario del sistema si mette sotto pressione, motivo per cui l'età pensionabile e i requisiti contributivi sono stati più volte rivisti al rialzo negli ultimi decenni.$$),

(NULL, 'Perché i camaleonti cambiano colore?', 'Bambino', '🧒', 'breve', 400, $$Molte persone pensano che i camaleonti cambino colore solo per nascondersi, ma in realtà lo fanno soprattutto per comunicare con altri camaleonti — per esempio per mostrare che sono spaventati, arrabbiati, o pronti ad accoppiarsi. Riescono a farlo perché sotto la loro pelle trasparente hanno strati speciali di cellule con minuscoli cristalli che riflettono la luce in modo diverso a seconda di come li "stringono" o li "allargano" — un po' come cambiare la disposizione di tanti specchietti colorati sotto la pelle per creare colori diversi.$$),

(NULL, 'Come funziona il carcere minorile in Italia?', 'Adulto', '👤', 'breve', 650, $$Il sistema penale minorile italiano è profondamente diverso da quello per adulti, orientato principalmente al recupero e alla rieducazione piuttosto che alla punizione pura, in linea con l'articolo 27 della Costituzione. I minori tra i 14 e i 18 anni possono essere ritenuti penalmente responsabili, ma il sistema privilegia fortemente misure alternative alla detenzione, come la "messa alla prova" (un percorso di reinserimento sociale supervisionato, che se completato con successo estingue il reato). Quando la detenzione è necessaria, avviene in Istituti Penali per i Minorenni (IPM), strutturalmente e organizzativamente separati dalle carceri per adulti, con un'attenzione specifica a percorsi educativi, scolastici e psicologici pensati per l'età dello sviluppo.$$),

(NULL, 'Perché ci vengono le occhiaie quando dormiamo poco?', 'Bambino', '🧒', 'breve', 380, $$La pelle sotto i tuoi occhi è molto più sottile e delicata rispetto al resto del viso, quasi trasparente, e sotto ci sono tantissimi piccoli vasi sanguigni. Quando dormi poco, questi vasi sanguigni tendono a dilatarsi leggermente e il sangue scorre più lentamente al loro interno, facendoli apparire più scuri attraverso la pelle sottile — un po' come vedere il colore blu-viola di una vena attraverso il polso. Ecco perché le occhiaie sembrano più evidenti quando sei stanco: non è che si crei qualcosa di nuovo, è che i vasi già presenti diventano più visibili.$$),

(NULL, 'Come funziona il processo di desalinizzazione dell''acqua di mare?', 'Universitario', '🎓', 'medio', 1150, $$La desalinizzazione converte l'acqua di mare (troppo salata per il consumo umano o l'agricoltura) in acqua dolce utilizzabile. La tecnologia oggi dominante è l'osmosi inversa: l'acqua salata viene spinta ad alta pressione attraverso membrane semipermeabili con pori microscopici, abbastanza piccoli da bloccare il passaggio di sali e altre impurità ma da permettere il passaggio delle molecole d'acqua, invertendo così il naturale processo osmotico (che normalmente spingerebbe l'acqua verso la soluzione più concentrata, non il contrario). Un metodo più vecchio, la distillazione termica, scalda l'acqua di mare fino all'evaporazione e poi condensa il vapore puro separatamente dai sali rimasti. Entrambi i processi sono energeticamente costosi (motivo per cui la desalinizzazione su larga scala è più diffusa in paesi ricchi di energia ma poveri d'acqua dolce, come diversi stati del Golfo Persico), e producono come sottoprodotto una salamoia molto concentrata il cui smaltimento in mare, se non gestito correttamente, può avere impatti ecologici significativi sull'ecosistema marino locale.$$),

(NULL, 'Perché lo zucchero fa "impazzire" i bambini (o è un mito)?', 'Adulto', '👤', 'breve', 700, $$Nonostante sia una convinzione molto diffusa tra genitori ed educatori, numerosi studi controllati in doppio cieco (dove né i bambini né chi li osserva sanno se hanno effettivamente consumato zucchero o un placebo) non hanno trovato una relazione causale diretta tra il consumo di zucchero e l'iperattività comportamentale nei bambini. L'effetto percepito sembra derivare più da un bias di aspettativa negli adulti: genitori che si aspettano un comportamento più agitato dopo che il bambino ha mangiato dolci (tipicamente in contesti come feste di compleanno, già di per sé stimolanti ed eccitanti indipendentemente dallo zucchero) tendono a interpretare comportamenti normali come "più agitati" del solito. Lo zucchero ha comunque effetti reali sulla salute a lungo termine se consumato in eccesso, semplicemente non è quello specifico del picco immediato di iperattività a cui viene comunemente attribuito.$$),

(NULL, 'Come fanno i sommergibili a immergersi e riemergere?', 'Ragazzo', '👨', 'medio', 850, $$I sommergibili controllano la loro profondità regolando la propria densità media tramite delle grandi camere vuote chiamate casse di zavorra, distribuite lungo lo scafo. Per immergersi, le casse vengono riempite d'acqua di mare, aumentando il peso complessivo del sommergibile finché non diventa più denso dell'acqua circostante e inizia ad affondare in modo controllato. Per riemergere, aria compressa ad alta pressione viene pompata nelle casse di zavorra, spingendo fuori l'acqua e riducendo di nuovo la densità complessiva del mezzo finché non torna a galleggiare verso la superficie. Durante la navigazione in immersione a profondità costante, il sommergibile mantiene un equilibrio preciso tra il proprio peso e la spinta di galleggiamento, regolando con precisione millimetrica la quantità d'acqua nelle casse tramite piccole regolazioni continue.$$),

(NULL, 'Perché le arance sono chiamate così anche se in inglese "orange" indica anche il colore?', 'Universitario', '🎓', 'medio', 1000, $$Curiosamente è stato il frutto a dare il nome al colore, e non il contrario, in molte lingue europee. Prima che l'arancia diventasse ampiamente conosciuta in Europa (introdotta dal commercio con il mondo arabo e asiatico intorno al XV-XVI secolo), la lingua inglese non aveva una parola dedicata specificamente per il colore arancione: veniva descritto genericamente come una sfumatura di "geoluread" (rosso-giallastro) in inglese antico. Il termine "orange" per il colore entrò nell'uso comune in inglese solo a partire dal XVI secolo, proprio in riferimento al colore caratteristico del frutto già diffuso, che a sua volta deriva dal termine sanscrito "naranga" attraverso persiano, arabo, e poi francese antico ("orenge").$$),

(NULL, 'Come funziona il pilota automatico dei robot aspirapolvere?', 'Esperto', '🧠', 'medio', 1050, $$I robot aspirapolvere moderni utilizzano tipicamente una combinazione di sensori LIDAR (Light Detection and Ranging, che emette impulsi laser e misura il tempo di ritorno per mappare la stanza in tre dimensioni) o sensori a infrarossi/telecamere, insieme ad algoritmi SLAM (Simultaneous Localization and Mapping). SLAM permette al robot di costruire progressivamente una mappa dell'ambiente circostante mentre determina contemporaneamente la propria posizione all'interno di quella mappa, senza avere alcuna conoscenza preesistente della disposizione della stanza. Una volta costruita una mappa sufficientemente accurata (spesso dopo la prima passata esplorativa), il robot pianifica percorsi di pulizia sistematici ed efficienti (tipicamente a righe parallele o a spirale) invece di muoversi in modo casuale, ed è in grado di riconoscere ostacoli, evitare cadute dai bordi tramite sensori di prossimità verso il basso, e tornare autonomamente alla base di ricarica quando la batteria è scarica o il lavoro è completato.$$),

(NULL, 'Perché a volte abbiamo il singhiozzo e come si fa a farlo passare?', 'Bambino', '🧒', 'breve', 400, $$Il singhiozzo succede quando il diaframma, il grande muscolo che ti aiuta a respirare posizionato sotto i polmoni, ha uno spasmo improvviso e involontario, contraendosi di scatto. Questo movimento brusco fa chiudere velocemente le tue corde vocali, producendo quel suono buffo "hic!" caratteristico. Non c'è un modo scientificamente certo al 100% per farlo passare subito, ma trattenere il respiro, bere acqua lentamente o respirare dentro un sacchetto di carta sembrano aiutare a "resettare" il ritmo respiratorio e calmare lo spasmo del diaframma.$$),

(NULL, 'Come funziona un contatore Geiger per rilevare la radioattività?', 'Universitario', '🎓', 'medio', 1050, $$Un contatore Geiger rileva la radiazione ionizzante attraverso un tubo riempito di gas a bassa pressione (tipicamente argon o neon), con un elettrodo centrale mantenuto ad alta tensione. Quando una particella radioattiva (raggio alfa, beta o gamma) attraversa il tubo, ionizza alcune molecole del gas al suo interno, liberando elettroni. Il campo elettrico intenso presente nel tubo accelera questi elettroni liberi, che a loro volta ionizzano altre molecole di gas in una reazione a cascata (effetto valanga), producendo un breve impulso di corrente elettrica misurabile. Ogni impulso corrisponde a una singola particella o raggio rilevato, e il dispositivo li conta e li converte tipicamente in un caratteristico "clic" udibile o in una lettura numerica di conteggi al minuto, un valore proporzionale (ma non linearmente equivalente) all'intensità della radioattività presente nell'ambiente misurato.$$),

(NULL, 'Perché ci laviamo i denti dopo mangiato e non prima?', 'Ragazzo', '👨', 'breve', 550, $$Dopo aver mangiato, soprattutto cibi zuccherati o acidi, i batteri naturalmente presenti nella bocca iniziano a produrre acidi che attaccano lo smalto dei denti, e i residui di cibo forniscono nutrimento a questi stessi batteri. Lavare i denti dopo i pasti rimuove questi residui e neutralizza in parte l'ambiente acido prima che possa danneggiare significativamente lo smalto. C'è però un'eccezione importante da conoscere: dopo aver mangiato cibi molto acidi (come agrumi o bevande gassate), i dentisti consigliano di aspettare almeno 20-30 minuti prima di lavarsi i denti, perché lo smalto risulta temporaneamente ammorbidito dall'acido e spazzolarlo subito potrebbe danneggiarlo meccanicamente invece di proteggerlo.$$),

(NULL, 'Come funziona il processo legislativo per approvare una legge in Italia?', 'Universitario', '🎓', 'medio', 1200, $$In Italia una proposta di legge può essere presentata dal Governo (disegno di legge), da parlamentari (proposta di legge), da un certo numero di cittadini tramite iniziativa popolare, o da altri soggetti previsti dalla Costituzione (Regioni, CNEL). Il testo deve essere approvato in identica formulazione da entrambe le Camere del Parlamento — Camera dei Deputati e Senato della Repubblica — secondo il cosiddetto sistema del bicameralismo perfetto: se una Camera modifica il testo, questo deve tornare all'altra per una nuova approvazione, in un processo (chiamato "navetta") che può ripetersi più volte finché entrambe le Camere non concordano sul medesimo testo. Una volta approvata da entrambe le Camere, la legge viene promulgata dal Presidente della Repubblica (che può, in casi eccezionali, rinviarla alle Camere con richiesta di riesame prima della promulgazione) e infine pubblicata nella Gazzetta Ufficiale, entrando in vigore generalmente dopo un periodo di 15 giorni (vacatio legis), salvo diversa indicazione specifica nel testo stesso.$$),

(NULL, 'Perché i delfini dormono con metà cervello alla volta?', 'Esperto', '🧠', 'medio', 950, $$I delfini, come altri cetacei, praticano un fenomeno chiamato sonno uniemisferico: un emisfero cerebrale entra in uno stato di sonno a onde lente mentre l'altro rimane sveglio e vigile, alternandosi periodicamente nel corso della giornata. Questo adattamento evolutivo risolve un problema fisiologico specifico dei mammiferi marini: a differenza dei pesci, i delfini devono risalire coscientemente in superficie per respirare aria atmosferica, un processo che richiede un controllo motorio volontario e non può essere completamente automatico come nella respirazione umana. Un sonno completo bi-emisferico li renderebbe temporaneamente incapaci di nuotare verso la superficie per respirare, con rischio letale di annegamento — il sonno uniemisferico permette quindi di mantenere sia il riposo neurologico necessario sia la vigilanza motoria e respiratoria continua indispensabile alla sopravvivenza.$$),

(NULL, 'Come funziona il processo di stagionatura del formaggio o del prosciutto?', 'Adulto', '👤', 'medio', 900, $$La stagionatura è un processo controllato di trasformazione biochimica in cui enzimi (naturalmente presenti nell'alimento o aggiunti tramite colture batteriche specifiche) scompongono gradualmente proteine e grassi in composti più semplici, sviluppando aromi, sapori e consistenze che non erano presenti nel prodotto fresco. Nel caso del formaggio, i batteri lattici e le muffe (in alcuni tipi specifici, come gorgonzola o brie) continuano a metabolizzare lentamente il latte cagliato per settimane o mesi, producendo composti aromatici complessi e modificando la struttura proteica che rende la consistenza più cremosa o friabile a seconda del tipo. Nel prosciutto, il processo di stagionatura coinvolge principalmente la disidratazione controllata (che concentra i sapori e previene la proliferazione batterica dannosa) insieme a reazioni enzimatiche proteolitiche che scompongono le proteine muscolari in amminoacidi liberi, responsabili del sapore intenso e caratteristico dei prosciutti stagionati a lungo (24-36 mesi per i prodotti di pregio).$$);
