-- Batch 8: 100 nuove spiegazioni mainstream, livello scelto in modo vario.

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché lo specchio inverte destra e sinistra ma non alto e basso?', 'Universitario', '🎓', 'medio', 1050, $$In realtà lo specchio non inverte affatto destra e sinistra: inverte solo la profondità, cioè l'asse perpendicolare alla superficie riflettente (avanti/indietro). L'illusione di uno scambio destra-sinistra nasce dal modo in cui noi interpretiamo l'immagine: quando immaginiamo la nostra immagine riflessa, mentalmente la "ruotiamo" di 180° per farla corrispondere a come vedremmo un'altra persona di fronte a noi, e quella rotazione mentale è ciò che scambia destra e sinistra nella nostra percezione, non lo specchio stesso. Se invece ti sdrai su un fianco davanti a uno specchio verticale, noterai che è "alto e basso" ad apparire invertito nella tua percezione, non più destra e sinistra — la prova che l'inversione dipende da come orientiamo noi stessi l'oggetto riflesso, non da una proprietà fisica dello specchio.$$),

(NULL, 'Come funziona il lievito madre?', 'Ragazzo', '👨', 'medio', 900, $$Il lievito madre (o pasta madre) è un impasto di farina e acqua lasciato fermentare naturalmente, che nel tempo cattura lieviti selvatici e batteri lattici presenti nell'aria e sulla farina stessa, creando una coltura vivente stabile. A differenza del lievito di birra industriale (un unico ceppo selezionato), il lievito madre contiene una comunità di microrganismi diversi che lavorano insieme: i lieviti producono anidride carbonica per far gonfiare l'impasto, mentre i batteri lattici producono acidi che danno al pane il caratteristico sapore leggermente acidulo e ne migliorano la conservabilità. Va "rinfrescato" regolarmente (aggiungendo altra farina e acqua) per tenere viva e attiva questa coltura di microrganismi, un po' come nutrire un organismo vivo che altrimenti si indebolirebbe nel tempo.$$),

(NULL, 'Perché i palloncini gonfiati con elio volano?', 'Bambino', '🧒', 'breve', 350, $$L'elio è un gas molto più leggero dell'aria che respiriamo normalmente. L'aria intorno a noi è fatta soprattutto di azoto e ossigeno, che sono più "pesanti" dell'elio. Quando riempi un palloncino con elio invece che con aria normale, il palloncino diventa più leggero dell'aria che lo circonda, e proprio come un sasso affonda nell'acqua ma un pezzo di legno galleggia, il palloncino "galleggia" verso l'alto nell'aria fino a salire in cielo.$$),

(NULL, 'Come si è formata la Luna?', 'Universitario', '🎓', 'medio', 1150, $$La teoria oggi più accreditata dagli scienziati è quella dell'impatto gigante (Giant Impact Hypothesis): circa 4,5 miliardi di anni fa, poco dopo la formazione della Terra, un corpo celeste delle dimensioni di Marte (soprannominato ipoteticamente Theia) avrebbe colpito la Terra con un impatto obliquo devastante. I detriti scagliati in orbita da questa collisione — una miscela di materiale del mantello terrestre e del corpo impattante — si sarebbero progressivamente aggregati per gravità formando la Luna nel giro di poche decine di migliaia di anni, un tempo estremamente breve su scala geologica. Questa teoria spiega elegantemente diverse osservazioni: la composizione chimica della Luna è molto simile a quella del mantello terrestre (soprattutto per gli isotopi dell'ossigeno), la Luna ha un nucleo ferroso proporzionalmente piccolo rispetto alla Terra, e il sistema Terra-Luna ha un momento angolare complessivo coerente con un impatto di quella scala.$$),

(NULL, 'Perché quando ci si taglia con un foglio di carta fa così male?', 'Adulto', '👤', 'breve', 600, $$I tagli da foglio di carta colpiscono tipicamente le dita, una delle zone del corpo con la più alta concentrazione di terminazioni nervose (necessaria per la precisione del tatto), quindi anche un taglio minuscolo attiva moltissimi recettori del dolore contemporaneamente. Il bordo di un foglio di carta, per quanto sembri innocuo, non è affatto liscio a livello microscopico: è seghettato e irregolare, il che produce una lacerazione dei tessuti più frastagliata e traumatica rispetto a un taglio netto fatto con una lama affilata. Inoltre, questi tagli sono spesso troppo superficiali per sanguinare abbondantemente: il sangue aiuterebbe a "sigillare" rapidamente la ferita e isolarla dall'aria, mentre un taglio da carta resta esposto più a lungo, con le terminazioni nervose scoperte a contatto diretto con l'aria e con qualsiasi cosa tocchi la zona.$$),

(NULL, 'Come funziona la carta di credito contactless?', 'Esperto', '🧠', 'medio', 1000, $$Le carte contactless utilizzano la tecnologia NFC (Near Field Communication), una forma di comunicazione radio a cortissimo raggio (pochi centimetri) basata sullo standard ISO/IEC 14443. Il chip nella carta contiene un'antenna passiva che non ha bisogno di batteria propria: viene alimentata induttivamente dal campo elettromagnetico generato dal terminale POS nel momento dell'avvicinamento, esattamente come funziona la ricarica wireless di uno smartphone su scala minore. Durante la transazione, il chip genera un codice crittografico dinamico univoco per quella specifica operazione (non trasmette mai il numero di carta "in chiaro" come farebbe una banda magnetica), rendendo estremamente difficile intercettare e riutilizzare i dati per transazioni fraudolente future — questo è anche il motivo per cui i pagamenti contactless sono generalmente considerati più sicuri, non meno sicuri, rispetto allo strisciamento della banda magnetica.$$),

(NULL, 'Perché i fenicotteri sono rosa?', 'Bambino', '🧒', 'breve', 380, $$I fenicotteri non nascono rosa: i piccoli hanno le piume grigie! Diventano rosa da adulti perché mangiano alghe e piccoli gamberetti che contengono una sostanza chiamata carotenoide (lo stesso pigmento che rende arancioni le carote). Quando i fenicotteri digeriscono questo cibo, il pigmento si deposita gradualmente nelle loro piume, rendendole sempre più rosa nel tempo. Se un fenicottero smettesse di mangiare questi alimenti specifici, col tempo le sue piume tornerebbero grigio-bianche!$$),

(NULL, 'Come funzionano i sottotitoli automatici generati dall''IA?', 'Esperto', '🧠', 'medio', 1100, $$I sistemi di sottotitolazione automatica combinano tipicamente il riconoscimento vocale automatico (ASR, Automatic Speech Recognition) con modelli linguistici che correggono e formattano l'output. Il segnale audio grezzo viene prima trasformato in uno spettrogramma (rappresentazione visiva delle frequenze nel tempo), che viene poi elaborato da una rete neurale (spesso basata su architetture transformer, come nel caso di Whisper di OpenAI) addestrata su enormi quantità di coppie audio-testo trascritte, per predire la sequenza di parole più probabile. Il modello deve gestire sfide significative come rumore di fondo, accenti regionali, sovrapposizione di parlanti e termini tecnici o nomi propri non comuni nel training set, motivo per cui l'accuratezza varia sensibilmente in base alla qualità dell'audio e alla somiglianza del contesto rispetto ai dati di addestramento originali.$$),

(NULL, 'Perché a volte il naso si tappa in aereo?', 'Ragazzo', '👨', 'breve', 550, $$Durante il decollo e soprattutto durante la discesa, la pressione dell'aria cambia rapidamente. Il tuo orecchio interno e i seni nasali sono collegati da piccoli canali (in particolare la tromba di Eustachio) che normalmente equalizzano la pressione tra l'interno e l'esterno del tuo corpo. Se questi canali sono già parzialmente ostruiti (per un raffreddore, un'allergia o semplicemente per conformazione anatomica), non riescono a equalizzare la pressione abbastanza velocemente rispetto al cambiamento rapido in cabina, e questo squilibrio di pressione può causare sia la sensazione di naso/orecchie tappate sia, in alcuni casi, un lieve dolore. Sbadigliare, deglutire o masticare una gomma aiuta perché attiva i muscoli che aprono la tromba di Eustachio, facilitando l'equalizzazione.$$),

(NULL, 'Come funziona il mercato azionario in generale?', 'Adulto', '👤', 'medio', 950, $$Il mercato azionario è un sistema organizzato in cui si comprano e vendono quote di proprietà (azioni) di aziende quotate pubblicamente. Quando compri un'azione, diventi comproprietario di una piccola parte di quell'azienda, con diritto a una quota proporzionale degli utili (spesso distribuiti come dividendi) e, in teoria, diritto di voto nelle assemblee societarie. Il prezzo delle azioni oscilla continuamente in base alla domanda e all'offerta, influenzata da fattori come i risultati economici dell'azienda, le prospettive future del settore, le condizioni macroeconomiche generali (tassi di interesse, inflazione) e semplicemente il sentiment collettivo degli investitori, che a volte si allontana significativamente dal valore "fondamentale" dell'azienda nel breve periodo. Nel lungo periodo, storicamente, i mercati azionari diversificati hanno generato rendimenti medi superiori all'inflazione, ma con oscillazioni significative anche di anno in anno.$$),

(NULL, 'Perché i gechi riescono a camminare sui soffitti?', 'Bambino', '🧒', 'breve', 400, $$Le zampe dei gechi sono ricoperte da milioni di peli piccolissimi, troppo piccoli per essere visti a occhio nudo, che si chiamano setae. Questi peli si attaccano alle superfici grazie a una forza fisica molto debole chiamata forza di Van der Waals, la stessa forza che tiene insieme le molecole nei materiali — presa singolarmente è debolissima, ma moltiplicata per i milioni di peli su ogni zampa diventa sufficiente a sostenere il peso dell'animale. Non è quindi una colla appiccicosa come potrebbe sembrare: i gechi possono staccare le zampe istantaneamente cambiando l'angolo di contatto dei peli, permettendo loro di correre velocissimi anche a testa in giù su un soffitto.$$),

(NULL, 'Come è nato il rock and roll?', 'Universitario', '🎓', 'medio', 1200, $$Il rock and roll emerse negli Stati Uniti tra la fine degli anni '40 e i primi anni '50 come fusione di diverse tradizioni musicali afroamericane preesistenti: il rhythm and blues, il boogie-woogie e il gospel, combinate con elementi del country e della musica popolare bianca. Artisti come Chuck Berry, Little Richard e Fats Domino, molti dei quali afroamericani, furono pionieri fondamentali del genere, sebbene fossero spesso relegati a un successo commerciale limitato dal razzismo sistemico dell'industria discografica dell'epoca, che favoriva invece "cover" bianche degli stessi brani. Il successo di Elvis Presley a metà anni '50 fu determinante per portare il genere a un pubblico bianco mainstream su scala nazionale, contribuendo a spianare la strada a una vera rivoluzione culturale giovanile che avrebbe influenzato profondamente musica, moda e costume per i decenni successivi, sebbene il suo ruolo nell'"appropriazione" di un genere di origine afroamericana resti tuttora oggetto di dibattito storico e culturale.$$),

(NULL, 'Perché scoppiettano le articolazioni quando le scrocchiamo?', 'Ragazzo', '👨', 'medio', 750, $$All'interno delle articolazioni (come le nocche delle dita) c'è un liquido lubrificante chiamato liquido sinoviale, che contiene gas disciolti (soprattutto anidride carbonica). Quando "scrocchi" un'articolazione, la stiri leggermente, aumentando improvvisamente lo spazio disponibile all'interno della capsula articolare. Questo cambiamento rapido di pressione fa formare (o collassare) piccole bolle di gas nel liquido, un processo chiamato cavitazione — è proprio la formazione o l'implosione rapida di queste bollicine a produrre il caratteristico suono "scrocchiante". Contrariamente a una credenza diffusa, gli studi scientifici disponibili non hanno trovato una correlazione significativa tra scrocchiarsi le dita regolarmente e lo sviluppo di artrite, anche se non è comunque consigliabile farlo con eccessiva forza o frequenza per altri motivi legati a legamenti e tendini.$$),

(NULL, 'Come funziona un motore elettrico di un''auto?', 'Esperto', '🧠', 'medio', 1050, $$Un motore elettrico automobilistico sfrutta il principio dell'induzione elettromagnetica: correnti elettriche alternate (in motori a corrente alternata, i più comuni nelle auto elettriche moderne, come i motori sincroni a magneti permanenti o i motori asincroni a induzione) generano un campo magnetico rotante nello statore (la parte fissa del motore), che interagisce con il campo magnetico del rotore (la parte mobile) generando una coppia meccanica che fa girare l'albero motore. A differenza di un motore a combustione interna, un motore elettrico può erogare la coppia massima praticamente da fermo (0 giri/minuto), il che spiega l'accelerazione istantanea e reattiva tipica delle auto elettriche, senza bisogno di un cambio a più marce complesso — spesso basta un singolo rapporto di riduzione fisso. L'efficienza energetica di un motore elettrico (tipicamente 85-95%) è inoltre nettamente superiore a quella di un motore a combustione interna (25-40%), poiché disperde molta meno energia sotto forma di calore.$$),

(NULL, 'Perché il cielo diventa rosso al tramonto?', 'Bambino', '🧒', 'breve', 380, $$Durante il giorno, quando il sole è alto nel cielo, la sua luce attraversa uno strato relativamente sottile di atmosfera per arrivare fino a noi, e vediamo prevalentemente il blu (che si disperde più facilmente). Al tramonto, invece, il sole è basso all'orizzonte e la sua luce deve attraversare uno strato di atmosfera molto più spesso per raggiungerti. Durante questo percorso più lungo, quasi tutta la luce blu viene dispersa lontano dalla tua vista, e quello che rimane e ti arriva agli occhi sono soprattutto le tonalità rosse, arancioni e rosa, che si disperdono meno facilmente — per questo il cielo al tramonto assume quei colori caldi e spettacolari.$$),

(NULL, 'Come funziona il sistema scolastico finlandese, spesso citato come modello?', 'Adulto', '👤', 'medio', 1000, $$Il sistema scolastico finlandese, spesso indicato come esempio a livello internazionale, si distingue per alcune scelte controcorrente rispetto ad altri paesi: pochissimi compiti a casa, quasi nessun test standardizzato prima dei 16 anni, giornate scolastiche più brevi con pause frequenti, e un forte investimento nella formazione degli insegnanti (in Finlandia insegnare richiede un master universitario ed è una professione molto selettiva e prestigiosa, paragonabile a medicina o legge in termini di status sociale). Il modello punta esplicitamente sull'equità piuttosto che sulla competizione: quasi tutte le scuole pubbliche hanno finanziamenti e qualità comparabili, riducendo drasticamente la necessità per le famiglie di "scegliere" la scuola migliore. È importante notare che questo modello si è sviluppato in un contesto sociale specifico (paese piccolo, alta fiducia nelle istituzioni, bassa disuguaglianza economica), il che rende complesso trasferirlo direttamente ad altri contesti nazionali molto diversi.$$),

(NULL, 'Perché ci sono fusi orari con mezz''ora di differenza (tipo l''India)?', 'Ragazzo', '👨', 'breve', 550, $$La maggior parte dei fusi orari nel mondo differisce di un'ora intera rispetto ai vicini, ma alcuni paesi (India, Iran, alcune zone dell'Australia) hanno scelto fusi orari con uno scarto di 30 o addirittura 45 minuti. Spesso questa scelta è motivata dalla posizione geografica reale del paese, che cadrebbe "a metà" tra due fusi standard se si seguisse rigorosamente la longitudine; in altri casi è una decisione politica per creare un unico fuso orario nazionale unificato che sia un compromesso ragionevole tra le diverse estremità geografiche est-ovest del paese, evitando di dividerlo in più fusi diversi che complicherebbero la vita quotidiana e gli affari interni.$$),

(NULL, 'Come funziona la fecondazione in vitro?', 'Universitario', '🎓', 'medio', 1200, $$La fecondazione in vitro (FIVET) è una tecnica di procreazione medicalmente assistita che prevede diverse fasi sequenziali. Prima, la paziente riceve una stimolazione ormonale controllata per favorire la maturazione simultanea di più ovociti (invece del singolo ovocita rilasciato naturalmente ogni ciclo), monitorata tramite ecografie ed esami del sangue. Gli ovociti maturi vengono poi prelevati chirurgicamente (pick-up ovocitario, procedura ambulatoriale sotto sedazione) e fecondati in laboratorio con gli spermatozoi, sia lasciandoli in coltura insieme sia tramite iniezione diretta di un singolo spermatozoo nell'ovocita (ICSI, tecnica usata soprattutto in caso di infertilità maschile). Gli embrioni che si sviluppano correttamente in coltura per alcuni giorni vengono valutati morfologicamente e uno o più vengono trasferiti nell'utero della donna, mentre eventuali embrioni sovrannumerari di buona qualità possono essere crioconservati per tentativi futuri.$$),

(NULL, 'Perché le formiche riescono a sollevare pesi enormi rispetto al loro corpo?', 'Bambino', '🧒', 'breve', 380, $$Le formiche riescono a sollevare fino a 50 volte il proprio peso corporeo, un po' come se tu riuscissi a sollevare un'automobile intera! Questo succede soprattutto perché più un animale è piccolo, più i suoi muscoli sono forti in proporzione al suo peso — è una regola della fisica legata a come cresce il volume (e quindi il peso) rispetto all'area dei muscoli quando un corpo si rimpicciolisce. In pratica, essere piccolissime è proprio il "segreto" che rende le formiche così sorprendentemente forti rispetto alle loro dimensioni.$$),

(NULL, 'Come funziona un algoritmo di compressione delle immagini (tipo JPEG)?', 'Scienziato', '🧪', 'lungo', 2000, $$Trasformata discreta del coseno: il formato JPEG suddivide l'immagine in blocchi di 8x8 pixel e applica a ciascuno la trasformata discreta del coseno (DCT), che converte i valori di luminosità/colore dal dominio spaziale al dominio delle frequenze, rappresentando il blocco come somma pesata di funzioni coseno a frequenze crescenti.

Quantizzazione: questa è la fase realmente "lossy" (con perdita) dell'algoritmo. Le componenti ad alta frequenza (dettagli fini, a cui l'occhio umano è meno sensibile secondo i modelli di percezione visiva) vengono quantizzate con una precisione molto più bassa rispetto alle componenti a bassa frequenza (variazioni graduali di colore, a cui l'occhio è più sensibile), riducendo drasticamente la quantità di informazione da codificare senza una perdita percettibile proporzionale.

Codifica entropica: dopo la quantizzazione, i coefficienti risultanti (spesso molti zeri, specialmente alle alte frequenze) vengono compressi ulteriormente senza perdita tramite codifica a lunghezza variabile (tipicamente Huffman), sfruttando la ridondanza statistica dei dati per ridurre ulteriormente lo spazio necessario.

Limiti e artefatti: la natura per blocchi dell'algoritmo produce i caratteristici "artefatti a blocchi" (blocking artifacts) visibili a compressioni molto aggressive, specialmente ai bordi tra blocchi da 8x8 pixel adiacenti quantizzati in modo molto diverso, ed è per questo che formati più recenti (come WebP o AVIF) usano trasformate e strategie di predizione più sofisticate per ridurre questi artefatti a parità di rapporto di compressione.$$);
