-- Batch 13: blocco finale per completare le 100 nuove spiegazioni richieste.

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché le banane diventano marroni se le mettiamo in frigo?', 'Bambino', '🧒', 'breve', 380, $$Le banane sono frutti tropicali abituati a temperature calde, e il freddo del frigorifero danneggia le loro cellule interne, un po' come un piccolo shock per la pianta. Questo danno fa uscire alcune sostanze chimiche dentro la buccia che, a contatto con l'aria, si scuriscono rapidamente, proprio come succede a una mela tagliata che lasci all'aria. La polpa dentro, sotto quella buccia scura, resta invece ancora perfettamente buona da mangiare per un po' di tempo, anche se la buccia sembra rovinata.$$),

(NULL, 'Come funziona il processo con cui viene stabilito il prezzo del petrolio a livello mondiale?', 'Adulto', '👤', 'medio', 900, $$Il prezzo del petrolio si forma principalmente sui mercati finanziari internazionali (le principali borse di riferimento sono quelle di Londra per il Brent e New York per il WTI), dove viene scambiato tramite contratti futures — accordi per comprare o vendere una certa quantità di greggio a una data futura e a un prezzo concordato oggi. Il prezzo riflette l'equilibrio tra domanda globale attesa (legata alla crescita economica mondiale, ai consumi industriali e dei trasporti) e offerta disponibile, quest'ultima fortemente influenzata dalle decisioni di produzione dell'OPEC+ (il cartello di paesi produttori che coordina volontariamente i livelli di produzione per influenzare i prezzi) e da fattori geopolitici imprevedibili (conflitti, sanzioni, tensioni in aree chiave di produzione o transito, come lo Stretto di Hormuz). Data l'importanza strategica del petrolio per l'intera economia globale, il suo prezzo è anche estremamente sensibile alle aspettative psicologiche degli operatori di mercato, non solo ai dati reali di domanda e offerta già disponibili.$$),

(NULL, 'Perché a volte facciamo confusione tra destra e sinistra?', 'Ragazzo', '👨', 'breve', 550, $$A differenza di concetti assoluti come "su" e "giù" (definiti chiaramente dalla gravità), destra e sinistra sono concetti puramente relativi che dipendono dal proprio orientamento personale in un dato momento — la stessa direzione può essere "destra" per una persona e "sinistra" per un'altra posizionata di fronte a lei. Il cervello deve quindi processare mentalmente una trasformazione spaziale più complessa per determinare destra/sinistra rispetto a su/giù, ed è un'abilità che si consolida più lentamente durante lo sviluppo infantile e resta, per alcune persone anche da adulte, leggermente meno automatica e più soggetta a errori sotto stress, distrazione o velocità di decisione richiesta (come mentre si guida o si seguono indicazioni rapide).$$),

(NULL, 'Come funziona il processo di tostatura del caffè che ne cambia il sapore?', 'Universitario', '🎓', 'medio', 1050, $$I chicchi di caffè verdi (non tostati) hanno un sapore erbaceo, quasi impercettibile rispetto a quello familiare del caffè che conosciamo — è interamente il processo di tostatura a sviluppare gli aromi complessi tipici. Durante la tostatura, i chicchi vengono riscaldati progressivamente fino a temperature di 200-230°C, innescando la reazione di Maillard (la stessa reazione chimica responsabile della doratura e degli aromi complessi nella carne cotta o nel pane) tra zuccheri e amminoacidi presenti nel chicco, che genera centinaia di nuovi composti aromatici. Il grado di tostatura (chiara, media, scura) determina profili di sapore molto diversi: tostature più chiare mantengono più acidità e note fruttate/floreali originarie del chicco, mentre tostature più scure sviluppano note più amare, tostate e di caramello bruciato, mascherando progressivamente le caratteristiche originarie specifiche della singola origine geografica del caffè.$$),

(NULL, 'Perché la neve è bianca se è fatta di acqua trasparente?', 'Bambino', '🧒', 'breve', 380, $$Un singolo fiocco di neve, o un piccolo pezzo di ghiaccio, sembra effettivamente trasparente o leggermente azzurrino se lo guardi da vicino. Ma la neve che vediamo per terra è fatta di milioni e milioni di minuscoli cristalli di ghiaccio ammassati insieme, con tantissime superfici diverse orientate in ogni direzione possibile. Ogni volta che la luce colpisce uno di questi tantissimi bordi, viene riflessa in una direzione diversa invece di attraversare dritta come farebbe in un unico pezzo di ghiaccio trasparente — con così tante riflessioni multiple e casuali di tutti i colori della luce insieme, l'effetto finale che vediamo è un bianco brillante e uniforme.$$),

(NULL, 'Come funziona un sistema di traduzione automatica come Google Translate?', 'Esperto', '🧠', 'medio', 1100, $$I sistemi di traduzione automatica moderni si basano su reti neurali di tipo transformer (la stessa architettura alla base dei moderni modelli linguistici), addestrate su enormi corpus di testi paralleli — coppie di frasi già tradotte professionalmente tra due o più lingue, spesso raccolte da documenti ufficiali multilingue, sottotitoli, e altre fonti pubbliche. A differenza dei sistemi più vecchi basati su regole grammaticali esplicite o su traduzione statistica frase per frase, gli approcci neurali moderni apprendono rappresentazioni vettoriali (embedding) che catturano il significato semantico di parole e frasi in uno spazio matematico condiviso tra le lingue, permettendo di generalizzare meglio a costruzioni linguistiche mai viste esplicitamente durante l'addestramento. Rimangono comunque sfide significative non completamente risolte: l'ambiguità semantica (parole con più significati a seconda del contesto), le espressioni idiomatiche non traducibili letteralmente, e soprattutto la traduzione accurata di lingue con pochissimi dati di addestramento disponibili (lingue "a basse risorse"), dove la qualità della traduzione resta sensibilmente inferiore rispetto a coppie linguistiche molto rappresentate come inglese-spagnolo.$$),

(NULL, 'Perché scricchiolano i pavimenti di legno quando ci cammini sopra?', 'Ragazzo', '👨', 'breve', 600, $$Il legno è un materiale naturale che si espande e si contrae leggermente in base a umidità e temperatura, e nel corso degli anni le assi di un pavimento possono seccarsi, restringersi leggermente o deformarsi in modo impercettibile. Quando cammini sopra, il tuo peso fa muovere minimamente le assi le une contro le altre, o contro i chiodi e le viti che le tengono fissate alla struttura sottostante — è proprio questo piccolo attrito tra superfici di legno, o tra legno e metallo dei fissaggi, a produrre il caratteristico suono scricchiolante che senti, tanto più frequente quanto più il pavimento è vecchio e il legno ha avuto tempo di muoversi e assestarsi nel tempo.$$),

(NULL, 'Come funziona la classificazione delle stelle in base al colore e alla temperatura?', 'Scienziato', '🧪', 'lungo', 1900, $$Classificazione spettrale di Harvard: le stelle vengono classificate in una sequenza di tipi spettrali (O, B, A, F, G, K, M, dalla più calda alla più fredda) basata sull'analisi delle righe di assorbimento presenti nel loro spettro luminoso, che riflettono la temperatura superficiale della stella e la conseguente ionizzazione degli elementi presenti nella sua atmosfera.

Relazione temperatura-colore: la temperatura superficiale determina direttamente il colore apparente della stella secondo la legge di Wien sullo spettro del corpo nero: le stelle di tipo O sono blu-violette (oltre 30.000 K), quelle di tipo G come il nostro Sole sono giallo-bianche (circa 5.500-6.000 K), mentre le stelle di tipo M sono rosse (sotto i 3.500 K) — contrariamente all'intuizione comune associata al fuoco, il blu rappresenta le temperature più alte e il rosso quelle più basse in astrofisica.

Diagramma H-R: il diagramma di Hertzsprung-Russell mette in relazione luminosità e temperatura (o tipo spettrale) di migliaia di stelle, rivelando pattern evolutivi fondamentali: la maggior parte delle stelle si colloca lungo una banda diagonale chiamata sequenza principale, dove trascorrono la gran parte della loro vita fondendo idrogeno in elio nel nucleo, mentre stelle giganti, supergiganti e nane bianche occupano posizioni distinte che riflettono fasi evolutive successive o conclusive del ciclo vitale stellare.

Limiti osservativi: la classificazione spettrale accurata richiede spettroscopia di qualità sufficiente, non sempre disponibile per stelle molto deboli o distanti; inoltre fattori come la rotazione stellare, la composizione chimica specifica e la presenza di campi magnetici intensi possono introdurre variazioni sottili nello spettro osservato che complicano una classificazione univoca e priva di ambiguità in casi limite.$$),

(NULL, 'Perché non dovremmo svegliare bruscamente qualcuno che sta sonnambulando?', 'Adulto', '👤', 'breve', 600, $$Il sonnambulismo avviene tipicamente durante le fasi di sonno profondo non-REM, in uno stato di parziale attivazione cerebrale in cui alcune aree motorie sono attive mentre le aree della coscienza e della piena consapevolezza restano largamente disattivate. Svegliare bruscamente una persona in questo stato può causare una condizione di confusione acuta e disorientamento intenso (nota come "inerzia del sonno" estrema), durante la quale la persona, ancora parzialmente in uno stato di coscienza alterata, potrebbe reagire con paura, confusione o persino aggressività involontaria e incontrollata verso chi la sta svegliando, semplicemente perché il cervello non ha avuto il tempo fisiologico necessario per transitare gradualmente dallo stato di sonno profondo alla piena veglia cosciente. È generalmente più sicuro guidare delicatamente la persona di nuovo a letto o assicurarsi solo che non si faccia male, piuttosto che tentare di svegliarla bruscamente.$$),

(NULL, 'Come funziona il processo con cui l''acqua diventa potabile in un impianto di depurazione?', 'Universitario', '🎓', 'medio', 1150, $$Il trattamento dell'acqua potabile in un acquedotto moderno segue tipicamente diverse fasi sequenziali. La coagulazione-flocculazione aggiunge sostanze chimiche (come solfato di alluminio) che fanno aggregare le particelle sospese più piccole in fiocchi più grandi e pesanti, facilitandone la rimozione successiva. La sedimentazione permette a questi fiocchi appesantiti di depositarsi sul fondo delle vasche per semplice gravità. La filtrazione, spesso attraverso strati di sabbia e carbone attivo, rimuove le particelle residue più fini e molti contaminanti chimici e organici tramite adsorbimento. Infine, la disinfezione (tipicamente con cloro, ozono o raggi UV) elimina i patogeni microbiologici residui (batteri, virus) prima della distribuzione nella rete idrica. Un residuo minimo di disinfettante (nel caso del cloro) viene generalmente mantenuto anche durante il trasporto nella rete, per proteggere l'acqua da eventuali contaminazioni successive lungo il percorso fino al rubinetto di casa.$$);
