-- Batch 4: ampliamento community spiegazioni (spazio, ambiente, economia,
-- linguistica, arte, salute).

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché la Luna ha sempre la stessa faccia rivolta verso di noi?', 'Ragazzo', '👨', 'medio', 800, $$La Luna impiega esattamente lo stesso tempo per girare su se stessa (rotazione) e per girare intorno alla Terra (rivoluzione): circa 27,3 giorni per entrambe. Questo fenomeno si chiama "rotazione sincrona" e non è un caso: nel corso di miliardi di anni, la forza di gravità della Terra ha rallentato la rotazione della Luna fino a "bloccarla" in questo equilibrio, un po' come quando fai girare una trottola e alla fine si ferma in una posizione stabile. Per questo dalla Terra vediamo sempre la stessa faccia della Luna, mentre l'altro lato (chiamato spesso, in modo impreciso, "il lato oscuro") lo abbiamo visto solo grazie alle sonde spaziali.$$),

(NULL, 'Perché il cambiamento climatico è considerato causato dall''uomo?', 'Universitario', '🎓', 'medio', 1300, $$Il consenso scientifico (oltre il 97% degli studi climatologici pubblicati) attribuisce il riscaldamento globale osservato dalla metà del XX secolo principalmente alle attività umane, in particolare alle emissioni di gas serra (anidride carbonica, metano) derivanti dalla combustione di combustibili fossili. Le prove principali includono: la correlazione temporale tra l'aumento delle concentrazioni di CO₂ atmosferica (misurate direttamente dal 1958 e ricostruite da carotaggi di ghiaccio per gli 800.000 anni precedenti) e l'aumento delle temperature medie globali; la "firma isotopica" del carbonio proveniente dai combustibili fossili, distinguibile da quello di origine naturale; e i modelli climatici, che riescono a riprodurre l'andamento storico delle temperature solo includendo il contributo antropico, non con le sole variabili naturali (attività solare, vulcanismo). L'effetto serra in sé è un fenomeno fisico noto e quantificato da oltre un secolo (Arrhenius, 1896).$$),

(NULL, 'Perché l''euro ha lo stesso valore in tutti i paesi che lo usano?', 'Adulto', '👤', 'breve', 700, $$L'euro è gestito da un'unica banca centrale, la Banca Centrale Europea (BCE), che decide la politica monetaria (tassi di interesse, quantità di moneta in circolazione) per tutta l'Eurozona in modo uniforme — non esistono più banche centrali nazionali indipendenti che possano stampare moneta o svalutare la propria valuta come accadeva prima con lira, marco o franco. Questo garantisce che un euro valga esattamente un euro ovunque nell'Eurozona, ma ha anche un costo: un singolo paese non può più usare la svalutazione della propria moneta per rendere le proprie esportazioni più competitive in caso di crisi economica localizzata, dovendo affidarsi ad altri strumenti (riforme interne, politiche fiscali) per adattarsi.$$),

(NULL, 'Perché alcune lingue hanno generi grammaticali (maschile/femminile) e altre no?', 'Universitario', '🎓', 'medio', 1150, $$Il genere grammaticale è un sistema di classificazione dei nomi che si è evoluto in modo indipendente in diverse famiglie linguistiche, spesso a partire da distinzioni originarie basate su categorie semantiche (animato/inanimato, o dimensione/forma), che nel tempo si sono grammaticalizzate perdendo gran parte della loro logica intuitiva originale. Le lingue romanze (italiano, spagnolo, francese) hanno ereditato il sistema a due generi dal latino classico, che ne aveva tre (perdendo il neutro). L'inglese invece ha perso quasi completamente il genere grammaticale nel corso della sua evoluzione storica (l'inglese antico ne aveva tre, come il tedesco moderno), mantenendolo solo nei pronomi personali (he/she/it). Non esiste una correlazione diretta tra la presenza del genere grammaticale e la complessità o "evoluzione" di una lingua: sono semplicemente scelte strutturali diverse che si sono consolidate nel tempo.$$),

(NULL, 'Come fanno gli artisti a creare il movimento nei quadri (senso del dinamismo)?', 'Esperto', '🧠', 'medio', 1050, $$Il senso di movimento in un'opera statica si ottiene attraverso diverse strategie compositive consolidate: le linee diagonali e le composizioni asimmetriche suggeriscono direzionalità e instabilità (in contrasto con la stasi delle composizioni simmetriche e orizzontali/verticali); la sfocatura selettiva di alcune parti della figura (tecnica esplicitamente teorizzata dal Futurismo italiano, es. Boccioni) simula la persistenza retinica del movimento reale; il contrasto cromatico e tonale guida l'occhio dello spettatore lungo un percorso preciso all'interno del quadro, creando una sequenza narrativa temporale anche in un'immagine fissa. Anche la scelta del momento rappresentato è cruciale: raffigurare un'azione nel suo punto di massima tensione (come il lancio di un giavellotto a metà gesto, non prima né dopo) sfrutta l'aspettativa dello spettatore rispetto a ciò che sta per accadere.$$),

(NULL, 'Perché a volte perdiamo l''appetito quando siamo stressati?', 'Adulto', '👤', 'breve', 650, $$Lo stress attiva il sistema nervoso simpatico e il rilascio di ormoni come il cortisolo e l'adrenalina, la stessa risposta "combatti o fuggi" che il corpo attiverebbe di fronte a un pericolo fisico immediato. In questa modalità, il corpo considera la digestione una priorità secondaria rispetto alla sopravvivenza: rallenta l'attività dello stomaco e dell'intestino, e l'adrenalina in particolare sopprime direttamente i segnali di fame. È lo stesso motivo per cui, paradossalmente, in altre persone lo stress cronico (diverso da quello acuto) produce l'effetto opposto, spingendo verso il cosiddetto "comfort eating": dipende da come il singolo organismo regola cortisolo e altri ormoni nel lungo periodo.$$),

(NULL, 'Come funziona il sistema immunitario contro un raffreddore?', 'Universitario', '🎓', 'medio', 1150, $$Quando un rinovirus (la causa più comune del raffreddore) infetta le cellule delle vie respiratorie superiori, il sistema immunitario innato risponde rapidamente attraverso cellule come i macrofagi e la produzione di interferoni, proteine che segnalano alle cellule vicine di attivare difese antivirali e che sono responsabili di molti sintomi tipici (febbre lieve, stanchezza, infiammazione delle mucose). Nel giro di alcuni giorni si attiva anche la risposta immunitaria adattativa: i linfociti B iniziano a produrre anticorpi specifici contro quel particolare ceppo virale, mentre i linfociti T killer eliminano le cellule già infettate. Poiché esistono oltre 200 ceppi virali diversi in grado di causare il raffreddore, e l'immunità sviluppata è per lo più specifica per ciascun ceppo, è possibile ammalarsi ripetutamente nel corso della vita anche con immunità individualmente efficace.$$),

(NULL, 'Perché i pinguini non riescono a volare ma nuotano benissimo?', 'Bambino', '🧒', 'breve', 380, $$Tantissimi anni fa gli antenati dei pinguini probabilmente sapevano volare, ma nel corso del tempo le loro ali si sono trasformate in pinne perfette per nuotare invece che per volare in aria. Le loro ossa sono più pesanti e piene (invece che cave e leggere come quelle degli altri uccelli che volano), il che le aiuta a stare sott'acqua invece che a librarsi in cielo. In pratica hanno "scambiato" la capacità di volare nell'aria con quella di volare sott'acqua, dove nuotano velocissimi cacciando pesci.$$),

(NULL, 'Come funziona la par condicio in TV durante le elezioni?', 'Adulto', '👤', 'breve', 650, $$La par condicio è una legge italiana (n. 28 del 2000) che obbliga le emittenti radiotelevisive, soprattutto quelle pubbliche, a garantire spazi e condizioni di accesso equilibrate a tutti i soggetti politici durante le campagne elettorali, evitando che un partito o un candidato ottenga una visibilità sproporzionata rispetto agli altri. In pratica, nei periodi elettorali le trasmissioni di informazione politica devono rispettare tempi di parola calcolati con precisione tra le diverse forze in campo, e viene vietata la pubblicità elettorale a pagamento sulle reti nazionali. L'Autorità per le Garanzie nelle Comunicazioni (AGCOM) vigila sul rispetto di queste regole e può sanzionare le emittenti inadempienti.$$),

(NULL, 'Perché lo spazio è così freddo se il Sole emette tanto calore?', 'Ragazzo', '👨', 'medio', 850, $$Il calore si trasmette in tre modi: conduzione, convezione e irraggiamento. Nello spazio vuoto non c'è materia (aria, acqua) che possa trasportare calore per conduzione o convezione, quindi l'unico modo in cui l'energia del Sole raggiunge un oggetto nello spazio è l'irraggiamento, cioè la radiazione elettromagnetica diretta. Un oggetto colpito direttamente dai raggi del Sole nello spazio può scaldarsi moltissimo (anche oltre 120°C sulla Luna, dal lato illuminato), ma se non riceve luce diretta (nell'ombra) si raffredda drasticamente, perché non c'è aria che trasporti calore per riscaldarlo indirettamente come avviene sulla Terra. Ecco perché "lo spazio è freddo" non è del tutto corretto: dipende moltissimo dall'essere o meno esposti direttamente alla luce solare.$$),

(NULL, 'Come mai i social media creano dipendenza?', 'Esperto', '🧠', 'medio', 1150, $$I social media sono progettati deliberatamente attorno a meccanismi di rinforzo a intervallo variabile, lo stesso principio psicologico che rende le slot machine così coinvolgenti: notifiche, like e nuovi contenuti arrivano in modo imprevedibile, il che attiva il rilascio di dopamina nel nucleo accumbens in modo più potente rispetto a una ricompensa prevedibile (l'incertezza stessa è ricompensante). Lo scroll infinito elimina i "punti di stop" naturali che in passato segnalavano la fine di un contenuto (come la fine di un giornale), rendendo più difficile per il cervello decidere autonomamente quando smettere. Inoltre, gli algoritmi di raccomandazione ottimizzano esplicitamente per il tempo di permanenza sulla piattaforma (metrica chiamata "engagement"), non per il benessere dell'utente, il che crea un disallineamento sistematico tra gli interessi dell'azienda e quelli della persona che usa il servizio.$$),

(NULL, 'Perché le cipolle ci fanno piangere quando le tagliamo?', 'Bambino', '🧒', 'breve', 380, $$Dentro la cipolla ci sono delle sostanze chimiche che, quando la tagli, si mescolano insieme e formano un gas invisibile che vola nell'aria fino ai tuoi occhi. Quando questo gas tocca la parte umida dei tuoi occhi, si trasforma in una sostanza leggermente irritante, un po' come un acido molto debole. Gli occhi allora producono lacrime per proteggersi e lavare via l'irritazione — ecco perché piangi anche se non sei affatto triste!$$),

(NULL, 'Come funzionano i test del DNA per trovare i parenti (tipo 23andMe)?', 'Esperto', '🧠', 'medio', 1100, $$Questi servizi analizzano centinaia di migliaia di SNP (polimorfismi a singolo nucleotide) nel tuo DNA tramite tecnologia a microarray, non l'intero genoma. Per trovare parentele, confrontano segmenti di DNA identici per discendenza (IBD, Identical By Descent) tra il tuo campione e quello di altri utenti nel database dell'azienda: più segmenti condivisi e più lunghi indicano un grado di parentela più stretto (i fratelli condividono circa il 50% del DNA, i cugini di primo grado circa il 12,5%). Per l'origine etnica/geografica, il tuo profilo genetico viene confrontato statisticamente con database di riferimento di popolazioni con origini geografiche note e documentate da generazioni, assegnando percentuali di "somiglianza" — un processo probabilistico, non una misura di identità assoluta, che può variare leggermente tra aziende diverse a seconda dei database di riferimento usati.$$),

(NULL, 'Perché il ghiaccio galleggia sull''acqua?', 'Universitario', '🎓', 'medio', 1000, $$L'acqua ha una proprietà anomala rispetto alla maggior parte delle sostanze: la sua forma solida (il ghiaccio) è meno densa della sua forma liquida. Questo accade perché, quando l'acqua si congela, le molecole si dispongono in una struttura cristallina esagonale tenuta insieme da legami idrogeno, che occupa più spazio rispetto alla disposizione più compatta e disordinata delle molecole nell'acqua liquida. Questa anomalia è cruciale per la vita sulla Terra: se il ghiaccio fosse più denso dell'acqua (come accade per quasi tutte le altre sostanze allo stato solido), affonderebbe sul fondo di laghi e oceani, che potrebbero congelare completamente dal basso verso l'alto durante l'inverno, rendendo la vita acquatica molto più difficile o impossibile in molte regioni.$$),

(NULL, 'Come funziona il sistema di quote latte/produzione europeo?', 'Adulto', '👤', 'breve', 500, $$Le quote di produzione dell'Unione Europea (storicamente famose per il latte, in vigore dal 1984 al 2015) erano un meccanismo per limitare la produzione totale di un determinato bene agricolo nei paesi membri, con l'obiettivo di evitare eccedenze che avrebbero fatto crollare i prezzi e danneggiato gli agricoltori. Ogni paese riceveva una quota massima produttiva; superarla comportava il pagamento di una penale (il "prelievo supplementare"). Il sistema venne progressivamente smantellato perché considerato troppo rigido e distorsivo del mercato, sostituito da meccanismi di sostegno diretto al reddito degli agricoltori (la Politica Agricola Comune moderna) meno legati ai volumi di produzione specifici.$$),

(NULL, 'Perché sbadigliamo, e perché è contagioso?', 'Ragazzo', '👨', 'medio', 750, $$Il motivo esatto per cui sbadigliamo non è ancora del tutto chiaro alla scienza: la vecchia idea che serva a "prendere più ossigeno" è stata in gran parte smentita da studi recenti, che suggeriscono invece un ruolo nel raffreddare il cervello o nel segnalare cambiamenti nello stato di allerta (sonno, noia, transizione tra attività). Il contagio dello sbadiglio, invece, è meglio studiato: sembra collegato all'empatia e ai neuroni specchio, gli stessi circuiti cerebrali che si attivano quando osserviamo le azioni altrui come se le stessimo compiendo noi. Non a caso, lo sbadiglio è più contagioso tra persone che si conoscono bene o provano empatia reciproca, mentre è meno contagioso guardando sbadigliare uno sconosciuto o, secondo alcuni studi, in persone con tratti autistici marcati.$$),

(NULL, 'Come funzionano gli anticorpi monoclonali usati in medicina?', 'Scienziato', '🧪', 'lungo', 1950, $$Origine e produzione: gli anticorpi monoclonali sono proteine identiche prodotte da un singolo clone di cellule immunitarie (linfociti B), tradizionalmente ottenuti tramite la tecnologia dell'ibridoma (fusione di un linfocita B produttore dell'anticorpo desiderato con una cellula mielomatosa immortale, tecnica sviluppata da Köhler e Milstein nel 1975, Nobel 1984). Le versioni moderne usate in terapia sono spesso "umanizzate" o completamente umane tramite ingegneria genetica, per ridurre il rischio di risposta immunitaria contro l'anticorpo terapeutico stesso.

Meccanismo d'azione: ogni anticorpo monoclonale è progettato per legarsi con altissima specificità a un singolo epitopo (regione bersaglio) su una proteina target, che può essere un recettore di superficie cellulare, un fattore di crescita circolante, o una componente virale. Il legame può neutralizzare direttamente il bersaglio (bloccando un recettore), marcare una cellula per la distruzione da parte del sistema immunitario (opsonizzazione), o veicolare un farmaco citotossico direttamente alle cellule bersaglio (antibody-drug conjugate).

Applicazioni cliniche: sono oggi utilizzati in oncologia (es. trastuzumab per tumori HER2-positivi), reumatologia (es. inibitori del TNF-alfa per artrite reumatoide), e sono stati centrali nella risposta terapeutica alla COVID-19 nelle sue fasi iniziali, prima della diffusione di varianti capaci di eludere il legame degli anticorpi originariamente sviluppati.

Limiti: la produzione è complessa e costosa rispetto ai farmaci a piccola molecola, richiede somministrazione parenterale (non sono biodisponibili per via orale, essendo degradati dal tratto digestivo), e l'efficacia può ridursi nel tempo se il bersaglio muta (come osservato con le varianti virali) o se il paziente sviluppa anticorpi contro il farmaco stesso (immunogenicità).$$);
