-- Batch 3: ampliamento community spiegazioni (scienza, corpo umano, storia,
-- tecnologia, animali), un livello/lunghezza per argomento.

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Come funziona un vaccino?', 'Universitario', '🎓', 'medio', 1150, $$Un vaccino espone il sistema immunitario a una versione innocua o inattivata di un patogeno (o a una sua componente, come nel caso dei vaccini a mRNA che codificano solo una proteina virale), senza causare la malattia vera e propria. Questo "addestramento controllato" induce la produzione di anticorpi specifici e, soprattutto, la formazione di cellule della memoria immunitaria (linfociti B e T a lunga vita) in grado di riconoscere rapidamente il patogeno reale in caso di esposizione futura. Alla successiva infezione, il sistema immunitario risponde molto più velocemente ed efficacemente rispetto a un primo contatto, spesso neutralizzando l'agente patogeno prima che causi sintomi rilevanti. L'immunità di gregge si ottiene quando una quota sufficiente della popolazione è vaccinata, riducendo la circolazione del patogeno anche per chi non può vaccinarsi.$$),

(NULL, 'Perché ci vengono le vertigini?', 'Bambino', '🧒', 'breve', 380, $$Dentro il tuo orecchio, in un punto che non vedi, ci sono dei piccoli tubicini pieni di liquido che aiutano il cervello a capire se sei dritto, girato o al contrario. Quando giri su te stesso velocemente, quel liquido continua a muoversi anche dopo che ti sei fermato, e il cervello si confonde: pensa che tu ti stia ancora muovendo anche se sei fermo! Per questo per un po' ti sembra che tutto giri intorno a te.$$),

(NULL, 'Come si formano gli arcobaleni?', 'Bambino', '🧒', 'breve', 400, $$Quando piove e allo stesso tempo c'è il sole, le goccioline d'acqua nell'aria funzionano come tanti piccolissimi prismi. La luce del sole, che sembra bianca ma in realtà contiene tutti i colori mescolati insieme, entra in ogni goccia e ne esce spezzata nei suoi colori, un po' come quando la luce attraversa un cristallo e crea riflessi colorati. Ecco perché vedi sempre i colori nello stesso ordine: rosso, arancione, giallo, verde, blu, viola.$$),

(NULL, 'Perché lo yogurt fa bene alla pancia?', 'Ragazzo', '👨', 'medio', 900, $$Lo yogurt contiene batteri "buoni" (soprattutto Lactobacillus e Bifidobacterium) che fanno parte della stessa famiglia di microrganismi che vivono naturalmente nel tuo intestino e ti aiutano a digerire il cibo. Quando mangi yogurt, questi batteri possono contribuire a mantenere in equilibrio il microbiota intestinale — l'insieme di miliardi di microrganismi che vivono nel tuo intestino — soprattutto dopo un ciclo di antibiotici, che tendono a eliminare anche i batteri buoni insieme a quelli cattivi. Non tutti gli yogurt sono uguali però: quelli con "fermenti lattici vivi" indicati in etichetta contengono batteri ancora attivi, mentre altri prodotti simili (pastorizzati dopo la fermentazione) no.$$),

(NULL, 'Come fanno gli aerei a volare?', 'Ragazzo', '👨', 'medio', 950, $$Le ali di un aereo sono progettate con una forma speciale (profilo alare) che fa muovere l'aria più velocemente sopra l'ala rispetto a sotto. Questo crea una differenza di pressione: l'aria sopra preme meno, quella sotto preme di più, e il risultato è una forza verso l'alto chiamata portanza. Più l'aereo va veloce, più portanza si genera, fino a superare il peso dell'aereo stesso e farlo sollevare da terra. I motori servono a spingere l'aereo in avanti abbastanza velocemente da generare questa portanza — non a farlo volare direttamente come un elicottero, che invece usa le pale rotanti per generare la spinta verso l'alto.$$),

(NULL, 'Perché il pane lievita?', 'Bambino', '🧒', 'breve', 380, $$Nell'impasto del pane si mette il lievito, che è fatto di minuscoli organismi vivi (funghi microscopici) che si nutrono degli zuccheri della farina. Mentre mangiano, questi organismi producono anidride carbonica, lo stesso gas delle bollicine nella Coca-Cola! Il gas forma tante piccole bolle dentro l'impasto, che si gonfia come un palloncino. Quando poi cuoci il pane nel forno, quelle bollicine restano intrappolate e danno al pane la sua consistenza soffice.$$),

(NULL, 'Come funziona la fotosintesi clorofilliana?', 'Universitario', '🎓', 'medio', 1200, $$La fotosintesi clorofilliana è il processo attraverso cui le piante convertono l'energia luminosa in energia chimica, utilizzando anidride carbonica e acqua per produrre glucosio e ossigeno. Il processo si articola in due fasi principali: la fase luminosa, che avviene nei tilacoidi dei cloroplasti e cattura l'energia della luce tramite la clorofilla per produrre ATP e NADPH, e la fase oscura (o ciclo di Calvin), che avviene nello stroma e utilizza quell'energia per fissare l'anidride carbonica in molecole organiche, principalmente glucosio. L'equazione complessiva semplificata è: 6CO₂ + 6H₂O + energia luminosa → C₆H₁₂O₆ + 6O₂. Questo processo è alla base della catena alimentare sulla Terra e responsabile della produzione dell'ossigeno atmosferico che respiriamo.$$),

(NULL, 'Perché sudiamo quando fa caldo?', 'Bambino', '🧒', 'breve', 350, $$Il tuo corpo funziona bene solo a una temperatura precisa, un po' come un forno che deve stare alla temperatura giusta. Quando fa molto caldo, il corpo produce sudore attraverso la pelle per raffreddarsi: quando il sudore evapora (cioè si trasforma in vapore e sparisce nell'aria), porta via con sé un po' di calore, proprio come quando soffi su una minestra calda per raffreddarla più in fretta.$$),

(NULL, 'Come funziona la blockchain?', 'Esperto', '🧠', 'lungo', 1900, $$Struttura dati distribuita: una blockchain è un registro (ledger) distribuito e immutabile, organizzato in blocchi collegati crittograficamente tramite hash: ogni blocco contiene l'hash del blocco precedente, rendendo qualsiasi alterazione retroattiva dei dati computazionalmente rilevabile, perché cambierebbe tutti gli hash successivi.

Meccanismi di consenso: poiché non esiste un'autorità centrale, la rete deve raggiungere un accordo condiviso sullo stato del registro attraverso algoritmi di consenso distribuito, i più noti dei quali sono il Proof of Work (richiede risoluzione di un problema computazionalmente costoso per validare un blocco, come in Bitcoin) e il Proof of Stake (la probabilità di validare un blocco è proporzionale alla quantità di criptovaluta bloccata come garanzia, come in Ethereum dal 2022).

Smart contract: piattaforme come Ethereum estendono il concetto di blockchain oltre il semplice trasferimento di valore, permettendo l'esecuzione di codice (smart contract) le cui condizioni sono verificate e applicate automaticamente dalla rete stessa, senza intermediari.

Limiti pratici: nonostante la narrazione di "decentralizzazione totale", in pratica molte blockchain mostrano una concentrazione significativa del potere di validazione (mining pool, grandi staker), e il throughput delle transazioni resta un ordine di grandezza inferiore rispetto ai sistemi di pagamento centralizzati tradizionali — un compromesso noto come "trilemma della blockchain" tra decentralizzazione, sicurezza e scalabilità.$$),

(NULL, 'Perché la Torre di Pisa è pendente?', 'Ragazzo', '👨', 'breve', 550, $$La Torre di Pisa ha iniziato a pendere già durante la sua costruzione, nel 1173, perché venne edificata su un terreno molto morbido e instabile — un misto di argilla, sabbia e conchiglie che non riusciva a sostenere uniformemente il peso della struttura. Quando i costruttori arrivarono al terzo piano, la torre aveva già iniziato a inclinarsi da un lato, ma invece di demolirla decisero di continuare, cercando addirittura di "correggere" la pendenza costruendo i piani successivi leggermente più dritti dal lato opposto — il che ha dato alla torre la sua caratteristica forma leggermente curva, oltre che pendente.$$),

(NULL, 'Come hanno costruito le piramidi egizie?', 'Universitario', '🎓', 'medio', 1200, $$Le teorie più accreditate dagli egittologi indicano che le piramidi (in particolare quella di Cheope, costruita intorno al 2560 a.C.) furono edificate da una forza lavoro organizzata di operai specializzati e stagionali, non da schiavi come vuole un mito diffuso — scoperte archeologiche di villaggi operai con evidenze di cure mediche e sepolture rispettose supportano questa interpretazione. I blocchi di pietra calcarea (in media 2,5 tonnellate ciascuno) venivano estratti da cave vicine e trasportati tramite slitte su percorsi bagnati per ridurre l'attrito, tecnica confermata da un dipinto tombale egizio del 1900 a.C. circa che mostra un operaio versare acqua davanti a una slitta. Per il sollevamento in altezza si ipotizzano rampe (dritte, a spirale o interne alla struttura stessa), sebbene il dettaglio esatto delle tecniche di sollevamento resti oggetto di dibattito accademico.$$),

(NULL, 'Perché i gatti fanno le fusa?', 'Bambino', '🧒', 'breve', 380, $$I gatti fanno le fusa soprattutto quando sono contenti e rilassati, per esempio quando li accarezzi. Ma non solo: a volte fanno le fusa anche quando sono spaventati o stanno male, un po' come se quel suono li aiutasse a calmarsi da soli, proprio come a te può fare bene canticchiare una canzone quando sei nervoso. Gli scienziati pensano che le vibrazioni delle fusa possano perfino aiutare le loro ossa e i muscoli a guarire più in fretta.$$),

(NULL, 'Come funziona il riconoscimento facciale dello smartphone?', 'Esperto', '🧠', 'medio', 1100, $$Il riconoscimento facciale sui dispositivi moderni (es. Face ID) utilizza tipicamente una combinazione di proiettore a infrarossi puntiformi (che proietta circa 30.000 punti invisibili sul volto) e una fotocamera a infrarossi che cattura la deformazione di quella griglia di punti sulla superficie 3D del viso, creando una mappa di profondità indipendente dalle condizioni di illuminazione ambientale. Questa mappa viene convertita in un vettore matematico tramite una rete neurale, confrontato localmente (non nel cloud, per motivi di privacy e sicurezza) con il vettore di riferimento registrato in un enclave sicura del processore (Secure Enclave su iOS). Il sistema è progettato per adattarsi gradualmente a piccoli cambiamenti dell'aspetto (occhiali, barba, invecchiamento) tramite aggiornamenti incrementali del modello di riferimento ogni volta che lo sblocco riesce con alta confidenza.$$),

(NULL, 'Perché ci vengono i lividi?', 'Bambino', '🧒', 'breve', 350, $$Sotto la pelle abbiamo tantissimi piccolissimi vasi sanguigni. Quando ti dai un colpo forte, alcuni di questi vasi si rompono e un po' di sangue esce, ma resta intrappolato sotto la pelle invece di uscire fuori. Quel sangue raccolto sotto la pelle è quello che vedi come macchia blu o viola: col passare dei giorni cambia colore (diventa verde, poi giallo) perché il corpo lo sta pian piano riassorbendo e ripulendo.$$),

(NULL, 'Come funziona un''eclissi solare?', 'Ragazzo', '👨', 'medio', 850, $$Un'eclissi solare succede quando la Luna si mette esattamente tra la Terra e il Sole, coprendo la sua luce e proiettando un'ombra sulla superficie terrestre. Sembra quasi un caso fortunato che accada: il Sole è circa 400 volte più grande della Luna, ma si trova anche circa 400 volte più lontano, quindi visti dalla Terra i due corpi sembrano avere quasi le stesse dimensioni nel cielo. Le eclissi totali sono visibili solo lungo una stretta fascia di territorio (il "percorso di totalità"), mentre in zone più ampie intorno si vede solo un'eclissi parziale.$$),

(NULL, 'Perché alcune persone sono mancine?', 'Adulto', '👤', 'breve', 650, $$La mancinità è determinata principalmente dall'organizzazione cerebrale: nella maggior parte delle persone l'emisfero sinistro del cervello, che controlla il lato destro del corpo, è dominante per il linguaggio e per le funzioni motorie fini, il che porta a una preferenza per la mano destra. Nei mancini questa dominanza è spesso invertita o meno marcata. Le cause esatte restano solo parzialmente comprese: si stima una componente genetica significativa (studi sui gemelli suggeriscono un'ereditabilità del 25% circa), ma nessun singolo "gene della mancinità" è stato identificato — probabilmente si tratta di un tratto poligenico influenzato anche da fattori prenatali. I mancini rappresentano circa il 10% della popolazione mondiale, una percentuale rimasta sorprendentemente stabile nel tempo e nelle culture.$$),

(NULL, 'Come si allena la memoria?', 'Adulto', '👤', 'medio', 1050, $$La memoria non è un "muscolo" nel senso letterale, ma risponde bene a pratiche mirate. La tecnica più efficace validata dalla ricerca è la ripetizione dilazionata (spaced repetition): rivedere un'informazione a intervalli crescenti nel tempo, invece di ripeterla tutta insieme, sfrutta il modo in cui il cervello consolida i ricordi a lungo termine. Altrettanto efficaci sono le tecniche di associazione visiva (come il "metodo dei loci", usato dai campioni di memoria, che collega informazioni a percorsi mentali familiari) e il semplice sonno di qualità, durante il quale il cervello consolida attivamente i ricordi della giornata. Al contrario, tecniche passive come rileggere più volte un testo senza mai testarsi attivamente sono tra le meno efficaci, nonostante siano le più usate intuitivamente da chi studia.$$),

(NULL, 'Perché i diamanti sono così duri?', 'Universitario', '🎓', 'medio', 1050, $$I diamanti sono composti esclusivamente da atomi di carbonio, esattamente come la grafite delle matite — la differenza enorme di durezza tra i due materiali dipende interamente dalla loro struttura cristallina. Nel diamante, ogni atomo di carbonio è legato ad altri quattro atomi tramite legami covalenti fortissimi disposti in una struttura tridimensionale tetraedrica estremamente regolare, che distribuisce lo stress meccanico in modo uniforme in tutte le direzioni. Nella grafite invece gli atomi di carbonio formano fogli piatti esagonali, legati fortemente all'interno di ogni foglio ma debolmente tra un foglio e l'altro (forze di Van der Waals), il che permette ai fogli di scivolare l'uno sull'altro — per questo la grafite è tenera e sfaldabile mentre il diamante è il materiale naturale più duro conosciuto.$$),

(NULL, 'Come funziona la fusione nucleare?', 'Scienziato', '🧪', 'lungo', 2100, $$Principio fisico: la fusione nucleare converte massa in energia unendo due nuclei atomici leggeri (tipicamente isotopi dell'idrogeno, deuterio e trizio) in un nucleo più pesante (elio), rilasciando energia secondo la relazione di equivalenza massa-energia E=mc², poiché il nucleo risultante ha una massa leggermente inferiore alla somma dei nuclei di partenza.

Condizioni necessarie: perché la fusione avvenga, i nuclei devono superare la repulsione elettrostatica reciproca (entrambi carichi positivamente), il che richiede temperature dell'ordine di 100-150 milioni di gradi Celsius e densità sufficienti per un tempo di confinamento adeguato — condizioni riassunte nel criterio di Lawson.

Approcci di confinamento: il confinamento magnetico (tokamak, come ITER in costruzione in Francia) utilizza campi magnetici intensi per contenere il plasma senza contatto con pareti materiali; il confinamento inerziale (come al National Ignition Facility) comprime rapidamente una piccola capsula di combustibile tramite laser di altissima potenza, innescando la fusione prima che il plasma si disperda.

Stato attuale e limiti: nel dicembre 2022 il NIF ha raggiunto per la prima volta un guadagno energetico netto (più energia prodotta dalla fusione che quella dei laser incidenti sul bersaglio), un traguardo scientifico storico ma ancora lontano dalla soglia di un reattore commercialmente redditizio (che richiede guadagno energetico "di impianto", includendo tutte le perdite del sistema, non solo del singolo esperimento). Le stime più ottimistiche per un reattore a fusione commerciale operativo restano nell'ordine dei decenni.$$),

(NULL, 'Perché a volte ci si addormenta senza accorgersene guardando la TV?', 'Ragazzo', '👨', 'breve', 550, $$Quando sei rilassato e fermo per un po' di tempo, soprattutto la sera dopo una giornata stancante, il tuo corpo inizia naturalmente a rallentare le sue funzioni in preparazione al sonno — il battito cardiaco si abbassa, i muscoli si rilassano. La luce blu-bassa e i suoni ripetitivi della TV in sottofondo, paradossalmente, possono aiutare questo processo invece di tenerti sveglio, soprattutto se il contenuto non è così coinvolgente da richiedere piena attenzione. Il cervello scivola quindi gradualmente dalla veglia al sonno leggero senza un momento preciso in cui "decidi" di addormentarti — motivo per cui spesso non te ne accorgi finché non ti risvegli di soprassalto.$$);
