-- Batch 5: ampliamento community spiegazioni (fisica quotidiana, storia
-- moderna, biologia, informatica, curiosita' varie).

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché il microonde scalda il cibo ma non il piatto?', 'Bambino', '🧒', 'breve', 400, $$Il forno a microonde produce delle onde invisibili che fanno vibrare velocissimamente le molecole d'acqua presenti nel cibo, e quel movimento rapidissimo crea calore, un po' come quando ti sfreghi velocemente le mani e si scaldano. Il piatto di ceramica o vetro invece ha pochissima acqua al suo interno, quindi le onde lo attraversano quasi senza scaldarlo direttamente. Se il piatto si scalda un po', è solo perché il cibo caldo sopra gli trasferisce un po' del suo calore per contatto.$$),

(NULL, 'Perché è caduto il Muro di Berlino?', 'Universitario', '🎓', 'medio', 1200, $$La caduta del Muro di Berlino, il 9 novembre 1989, fu il risultato di una combinazione di fattori economici, politici e sociali accumulatisi per anni nel blocco sovietico. La perestrojka e la glasnost di Gorbaciov avevano già allentato il controllo centrale sovietico sui paesi satelliti, incoraggiando riforme in Ungheria e Polonia. La crisi economica della Germania Est, incapace di reggere il confronto con il boom della Germania Ovest, alimentava un malcontento crescente. L'evento scatenante immediato fu però in parte accidentale: durante una conferenza stampa, un funzionario del governo della DDR, Günter Schabowski, annunciò per errore (o per confusione sulle tempistiche) che i cittadini potevano attraversare liberamente il confine "immediatamente", invece che con le procedure graduali previste. Migliaia di berlinesi orientali si radunarono ai checkpoint quella sera stessa, e le guardie di frontiera, sopraffatte e senza ordini chiari, finirono per aprire i cancelli.$$),

(NULL, 'Perché non riusciamo a solleticarci da soli?', 'Ragazzo', '👨', 'breve', 550, $$Il cervello ha un sistema che distingue tra sensazioni causate da noi stessi e sensazioni causate dall'esterno, per non sovraccaricarsi di informazioni prevedibili. Il cervelletto prevede esattamente le conseguenze sensoriali dei nostri stessi movimenti (sa già cosa sentirai un attimo prima che tu ti muova) e "smorza" quella sensazione in anticipo. Quando invece è qualcun altro a toccarti, il cervello non ha quella previsione anticipata, quindi la sensazione arriva "a sorpresa" ed è molto più intensa — per questo il solletico funziona solo se lo fa un'altra persona (o, in alcuni esperimenti, un dispositivo con un ritardo temporale imprevedibile rispetto al tuo movimento).$$),

(NULL, 'Come funziona il protocollo di sicurezza HTTPS?', 'Esperto', '🧠', 'lungo', 1900, $$Handshake TLS: quando ti connetti a un sito HTTPS, il browser e il server eseguono un handshake TLS (Transport Layer Security) per stabilire una connessione cifrata: il server presenta un certificato digitale (firmato da un'autorità di certificazione riconosciuta) che ne conferma l'identità, e le due parti negoziano un algoritmo di cifratura condiviso.

Crittografia ibrida: per motivi di efficienza, TLS combina crittografia asimmetrica e simmetrica. La crittografia a chiave pubblica (asimmetrica, come RSA o Diffie-Hellman a curva ellittica) viene usata solo per scambiarsi in modo sicuro una chiave di sessione condivisa, perché è computazionalmente costosa. Il traffico effettivo della sessione viene poi cifrato con un algoritmo simmetrico molto più veloce (tipicamente AES) usando quella chiave condivisa.

Autenticazione dell'identità: il certificato del server viene verificato tramite una catena di fiducia (chain of trust) che risale fino a un'autorità di certificazione root, i cui certificati sono preinstallati nel browser o nel sistema operativo. Se la catena non è valida (certificato scaduto, autofirmato, o dominio non corrispondente), il browser mostra un avviso di sicurezza.

Perfect Forward Secrecy: le implementazioni moderne di TLS (1.3 in particolare) usano chiavi di sessione effimere generate ad ogni connessione, garantendo che la compromissione futura della chiave privata a lungo termine del server non permetta di decifrare retroattivamente il traffico intercettato in passato.$$),

(NULL, 'Perché alcune persone diventano daltoniche?', 'Universitario', '🎓', 'medio', 1000, $$Il daltonismo è quasi sempre una condizione genetica legata al cromosoma X, che colpisce i coni retinici — le cellule fotorecettrici responsabili della visione dei colori. Esistono tre tipi di coni, sensibili rispettivamente al rosso, verde e blu; il daltonismo più comune (deuteranomalia/protanomalia, insieme oltre il 95% dei casi) coinvolge un'alterazione o assenza dei coni sensibili al rosso o al verde, rendendo difficile distinguere queste due tonalità. Essendo il gene coinvolto sul cromosoma X, e gli uomini avendo un solo cromosoma X (contro i due delle donne), il daltonismo è molto più comune nei maschi (circa 8% degli uomini contro meno dell'1% delle donne), perché nelle donne un secondo cromosoma X sano è spesso sufficiente a compensare la mutazione sull'altro.$$),

(NULL, 'Perché lo Space Shuttle non viene più usato dalla NASA?', 'Adulto', '👤', 'breve', 700, $$Il programma Space Shuttle fu ritirato definitivamente nel 2011 per una combinazione di motivi economici e di sicurezza. I costi operativi per lancio erano risultati molto più alti delle stime originali (che prevedevano un veicolo riutilizzabile "economico" come un aereo di linea) — ogni missione costava centinaia di milioni di dollari. Inoltre, due disastri catastrofici (Challenger nel 1986 e Columbia nel 2003, con la perdita di tutti gli equipaggi) avevano evidenziato rischi strutturali intrinsechi al design dello Shuttle. La NASA ha quindi deciso di concentrare le risorse su una nuova generazione di veicoli, affidando il trasporto orbitale di routine a partner commerciali (SpaceX con Crew Dragon, Boeing con Starliner) mentre sviluppa missioni più ambiziose verso la Luna e Marte con il programma Artemis.$$),

(NULL, 'Come funziona la memoria a breve e lungo termine nel cervello?', 'Universitario', '🎓', 'medio', 1150, $$La memoria a breve termine (o memoria di lavoro) trattiene una quantità limitata di informazioni (tradizionalmente stimata in 7±2 elementi, oggi ritenuta più vicina a 4) per pochi secondi o minuti, mantenute attive tramite circuiti neurali nella corteccia prefrontale. Perché un'informazione passi alla memoria a lungo termine, deve subire un processo di consolidamento, che coinvolge in modo cruciale l'ippocampo: questa struttura funge da "centro di smistamento temporaneo" che gradualmente trasferisce e stabilizza le tracce mnestiche nella corteccia cerebrale per l'archiviazione permanente, un processo che avviene in parte attivamente durante il sonno. A differenza della memoria a breve termine, la memoria a lungo termine non ha limiti di capacità noti e può conservare informazioni per l'intera vita, sebbene il recupero (non necessariamente la traccia stessa) possa indebolirsi nel tempo senza rinforzo.$$),

(NULL, 'Perché le zanzare pungono alcune persone più di altre?', 'Ragazzo', '👨', 'medio', 800, $$Le zanzare femmine (solo loro pungono, per ottenere le proteine del sangue necessarie a produrre le uova) sono attratte principalmente dall'anidride carbonica che espiriamo e da composti chimici specifici presenti nel sudore e sulla pelle. Persone con un metabolismo più alto (che producono più CO₂), donne in gravidanza, chi ha bevuto alcolici di recente, o chi ha semplicemente una composizione batterica cutanea diversa risultano più attraenti per le zanzare. Anche il gruppo sanguigno sembra giocare un ruolo secondo alcuni studi (il gruppo 0 risulterebbe leggermente più attraente), sebbene l'effetto combinato di CO₂, sudore e temperatura corporea resti il fattore predominante rispetto alla genetica del sangue.$$),

(NULL, 'Come funziona un frigorifero per raffreddare il cibo?', 'Ragazzo', '👨', 'medio', 900, $$Un frigorifero non "produce freddo" in senso letterale, ma sposta il calore da dentro (lo scomparto dove metti il cibo) a fuori (il retro del frigo, dove infatti senti aria calda). Questo avviene grazie a un gas refrigerante che circola in un circuito chiuso: un compressore lo comprime facendolo diventare molto caldo, poi il gas passa attraverso serpentine esterne (dietro il frigo) dove cede calore all'ambiente e si raffredda, condensandosi in liquido. Questo liquido passa poi attraverso una valvola che ne riduce bruscamente la pressione, facendolo espandere ed evaporare dentro il frigorifero: l'evaporazione assorbe calore dall'interno del frigo, raffreddandolo. Il gas poi torna al compressore e il ciclo ricomincia continuamente.$$),

(NULL, 'Perché in Italia esistono così tanti dialetti diversi?', 'Universitario', '🎓', 'medio', 1150, $$La straordinaria varietà dialettale italiana ha radici storiche profonde: a differenza di paesi come la Francia o l'Inghilterra, che raggiunsero un'unità politica centralizzata molto prima, la penisola italiana rimase frammentata in una moltitudine di stati indipendenti (repubbliche marinare, signorie, stati pontifici, regni) per gran parte della sua storia, fino all'Unità d'Italia nel 1861. Ogni territorio sviluppò la propria evoluzione linguistica a partire dal latino volgare locale, con influenze diverse a seconda delle dominazioni straniere subite (araba in Sicilia, spagnola nel Sud, francese e austriaca al Nord). L'italiano standard moderno, basato sul fiorentino letterario (per il prestigio di Dante, Petrarca e Boccaccio), si diffuse come lingua nazionale comune solo tardivamente, soprattutto grazie alla scuola dell'obbligo post-unitaria e, in modo determinante, alla televisione nel dopoguerra — prima di allora la maggioranza della popolazione parlava correntemente solo il proprio dialetto locale.$$),

(NULL, 'Perché il caffè ci sveglia?', 'Bambino', '🧒', 'breve', 380, $$Nel tuo cervello c'è una sostanza chiamata adenosina che si accumula pian piano durante il giorno e ti fa sentire stanco — più adenosina c'è, più hai sonno. La caffeina del caffè ha una forma molto simile all'adenosina e riesce a occupare i suoi "parcheggi" nel cervello senza però dare il messaggio di stanchezza. Così, per un po' di tempo, il tuo cervello non riceve il segnale "sei stanco" anche se l'adenosina è ancora lì, ed è per questo che ti senti più sveglio e attivo dopo aver bevuto il caffè.$$),

(NULL, 'Come funzionano le previsioni del tempo?', 'Ragazzo', '👨', 'medio', 900, $$Le previsioni meteo si basano su enormi quantità di dati raccolti in tempo reale da satelliti, stazioni meteo a terra, palloni sonda e navi/aerei, che misurano temperatura, pressione, umidità e vento a diverse altitudini in tutto il mondo. Questi dati vengono inseriti in modelli matematici complessi (basati sulle equazioni della fluidodinamica) eseguiti su supercomputer potentissimi, che simulano come l'atmosfera evolverà nelle ore e nei giorni successivi. Poiché l'atmosfera è un sistema caotico (piccolissime differenze iniziali nei dati possono portare a risultati molto diversi dopo alcuni giorni — il celebre "effetto farfalla"), le previsioni diventano naturalmente meno precise man mano che si estendono nel tempo: sono generalmente molto affidabili a 1-3 giorni, ragionevolmente accurate fino a una settimana, e sempre più incerte oltre.$$),

(NULL, 'Perché i muscoli fanno male il giorno dopo un allenamento intenso?', 'Adulto', '👤', 'breve', 700, $$Il dolore muscolare ritardato (DOMS, Delayed Onset Muscle Soreness), che tipicamente si manifesta 24-48 ore dopo uno sforzo insolito o intenso, deriva da microscopiche lacerazioni nelle fibre muscolari, soprattutto durante contrazioni eccentriche (quando il muscolo si allunga sotto tensione, come nella fase di discesa di uno squat). Contrariamente a una credenza diffusa, non è causato dall'accumulo di acido lattico, che viene smaltito dal corpo entro un'ora circa dall'esercizio. Il dolore è invece legato al processo infiammatorio di riparazione che il corpo attiva per ricostruire e rinforzare le fibre danneggiate — un processo che, paradossalmente, è alla base dell'adattamento e della crescita muscolare nel tempo, motivo per cui allenarsi regolarmente riduce progressivamente l'intensità del DOMS a parità di sforzo.$$),

(NULL, 'Come si decide il fuso orario di un paese?', 'Adulto', '👤', 'breve', 650, $$In teoria i fusi orari dovrebbero seguire le linee di longitudine (24 fusi da 15 gradi ciascuno, corrispondenti a un'ora di differenza), ma in pratica i confini sono spesso adattati per motivi politici, economici e pratici: un intero paese o regione sceglie di solito un unico fuso orario anche se attraversa più fusi geografici teorici, per facilitare commerci, trasporti e comunicazioni interne. La Cina, ad esempio, usa un unico fuso orario nazionale nonostante la sua estensione geografica corrisponderebbe a circa 5 fusi diversi, una scelta motivata dall'unità politica e amministrativa. Alcuni paesi usano perfino fusi orari con scarti di 30 o 45 minuti rispetto all'ora "intera" (come India o Nepal), spesso per motivi storici o per differenziarsi simbolicamente dai vicini.$$),

(NULL, 'Perché la Coca-Cola sgasata perde le bollicine più in fretta se lasciata al caldo?', 'Bambino', '🧒', 'breve', 380, $$Le bollicine della Coca-Cola sono anidride carbonica disciolta nel liquido sotto pressione. Il gas riesce a stare "intrappolato" meglio nel liquido quando questo è freddo, un po' come se il freddo lo tenesse più stretto e fermo. Quando il liquido si scalda, le sue molecole si muovono più velocemente e agitate, ed è più facile per il gas sfuggire verso l'alto e disperdersi nell'aria — ecco perché una bibita calda diventa "sgasata" molto più in fretta di una fredda.$$),

(NULL, 'Come funziona un algoritmo di raccomandazione (tipo quello di Netflix)?', 'Esperto', '🧠', 'medio', 1150, $$I sistemi di raccomandazione moderni combinano tipicamente due approcci principali: il filtraggio collaborativo, che identifica pattern tra utenti con gusti simili (se molte persone che hanno apprezzato il film A hanno apprezzato anche il film B, il sistema ti suggerirà B se hai apprezzato A), e il filtraggio basato sui contenuti, che analizza le caratteristiche intrinseche degli oggetti stessi (genere, attori, tag) per suggerire elementi simili a quelli già graditi. I sistemi più avanzati usano reti neurali di deep learning per apprendere rappresentazioni latenti (embedding) sia degli utenti che dei contenuti in uno spazio matematico condiviso, dove la "vicinanza" tra vettori predice l'affinità di gradimento. Un limite noto di questi sistemi è la cosiddetta "bolla di filtraggio" (filter bubble): ottimizzando per l'engagement immediato, tendono a rinforzare le preferenze già esistenti dell'utente piuttosto che esporlo a contenuti realmente nuovi o diversi.$$),

(NULL, 'Perché la panna montata si smonta se la sbatti troppo?', 'Ragazzo', '👨', 'breve', 550, $$Quando monti la panna, stai intrappolando piccolissime bolle d'aria dentro una rete di grassi che si formano dal latte, un po' come costruire una struttura solida ma delicata fatta di bolle e grasso. Se continui a sbattere oltre il punto giusto, quella struttura viene disturbata troppo: i grassi iniziano ad aggregarsi tra loro in modo eccessivo, l'aria intrappolata fuoriesce, e il liquido (siero) che era rimasto legato all'interno si separa. Il risultato è una consistenza granulosa e liquida invece che soffice — a quel punto, sbattendo ancora di più, si arriva addirittura a formare il burro, perché è esattamente lo stesso principio (separazione grasso/siero) portato all'estremo.$$),

(NULL, 'Come funziona il carcere a vita (ergastolo) in Italia?', 'Adulto', '👤', 'breve', 600, $$L'ergastolo in Italia è teoricamente una pena detentiva senza fine prestabilita, ma nella pratica non equivale quasi mai a una reclusione perpetua effettiva: dopo un periodo minimo (generalmente 26 anni, riducibile con la liberazione condizionale in presenza di comportamento e percorso rieducativo positivi), il condannato può accedere a benefici penitenziari progressivi come permessi premio, semilibertà e infine la liberazione condizionale definitiva. Esiste anche una forma più severa, l'ergastolo "ostativo" (per reati di particolare gravità, come mafia o terrorismo), che preclude questi benefici salvo collaborazione con la giustizia — un regime più volte oggetto di pronunce della Corte Costituzionale e della Corte Europea dei Diritti dell'Uomo per il suo possibile contrasto con il principio di rieducazione della pena sancito dalla Costituzione italiana.$$);
