-- Batch 11: altre spiegazioni mainstream, livello vario.

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché i limoni non marciscono facilmente come altri frutti?', 'Bambino', '🧒', 'breve', 380, $$I limoni contengono moltissimo acido citrico, la stessa sostanza che dà loro il sapore aspro. Questo acido crea un ambiente molto ostile per i batteri e le muffe che normalmente fanno marcire la frutta, perché la maggior parte di questi microrganismi non riesce a sopravvivere bene in condizioni così acide. Inoltre la buccia spessa del limone protegge la polpa interna da urti e da microrganismi esterni meglio di frutti dalla buccia più sottile e delicata, come pesche o prugne, che marciscono molto più in fretta.$$),

(NULL, 'Come funziona un sistema di navigazione satellitare come Google Maps quando calcola il traffico?', 'Esperto', '🧠', 'medio', 1050, $$I servizi di navigazione moderni stimano il traffico in tempo reale aggregando in forma anonima i dati di posizione GPS provenienti da milioni di smartphone degli utenti che hanno attivato la condivisione della posizione: velocità e densità di spostamento su ogni tratto stradale vengono confrontate con la velocità di riferimento in condizioni di traffico scorrevole, permettendo di rilevare rallentamenti o congestioni con un ritardo di pochi minuti. Questi dati vengono combinati con informazioni storiche (pattern tipici di traffico per quell'ora, giorno della settimana, stagione) e con dati strutturali su incidenti segnalati dagli stessi utenti o da fonti ufficiali, per generare non solo lo stato attuale del traffico ma anche previsioni a breve termine su come evolverà nei prossimi minuti, permettendo al sistema di suggerire percorsi alternativi prima ancora che una congestione si manifesti completamente.$$),

(NULL, 'Perché a volte facciamo un piccolo scatto involontario del corpo appena ci addormentiamo?', 'Ragazzo', '👨', 'medio', 700, $$Questo fenomeno si chiama scossa ipnica (o mioclono ipnico) e colpisce la maggior parte delle persone almeno occasionalmente. Una delle teorie più accreditate suggerisce che, mentre il corpo si rilassa progressivamente verso il sonno, il cervello a volte interpreta erroneamente questo rilassamento muscolare come un segnale di "caduta", attivando un riflesso protettivo istintivo di risveglio improvviso e contrazione muscolare — un residuo evolutivo forse legato ai nostri antenati che dormivano su rami degli alberi, dove un rilassamento eccessivo poteva davvero significare il rischio reale di cadere. Il fenomeno è generalmente innocuo e più frequente in condizioni di stanchezza accumulata, stress, o consumo elevato di caffeina.$$),

(NULL, 'Come funziona il processo di produzione della carta dalla legno?', 'Universitario', '🎓', 'medio', 1050, $$La produzione della carta parte dalla trasformazione del legno in polpa di cellulosa, attraverso due metodi principali. Il processo meccanico macina fisicamente il legno in fibre, con rese elevate ma qualità inferiore (usato per carta da giornale, che ingiallisce rapidamente per la presenza residua di lignina). Il processo chimico (kraft, il più diffuso industrialmente) cuoce i trucioli di legno in una soluzione chimica alcalina ad alta temperatura e pressione, dissolvendo selettivamente la lignina (il "collante" naturale che tiene insieme le fibre di cellulosa nel legno) e liberando fibre di cellulosa più pure e resistenti, adatte a carte di qualità superiore. La polpa risultante viene sbiancata (se necessario), diluita in una sospensione acquosa molto liquida, e stesa su una rete mobile in un macchinario continuo che rimuove progressivamente l'acqua, pressa e asciuga il foglio continuo di carta, arrotolandolo infine in enormi bobine pronte per la trasformazione successiva.$$),

(NULL, 'Perché il nostro corpo ha bisogno di vitamina D e perché la prendiamo dal sole?', 'Bambino', '🧒', 'breve', 400, $$La vitamina D aiuta il tuo corpo ad assorbire il calcio dal cibo, quel minerale importantissimo per costruire ossa e denti forti. La cosa speciale della vitamina D è che il tuo corpo può produrla da solo, ma ha bisogno della luce del sole per farlo: quando i raggi del sole toccano la tua pelle, alcune sostanze presenti nella pelle stessa si trasformano gradualmente in vitamina D attiva, un po' come una piccola fabbrica solare naturale che hai proprio sotto la pelle.$$),

(NULL, 'Come funziona il processo di brevettazione di un''invenzione?', 'Adulto', '👤', 'medio', 900, $$Un brevetto è un diritto di esclusiva temporaneo (tipicamente 20 anni dalla data di deposito) che lo Stato concede a chi ha inventato qualcosa di nuovo, originale e applicabile industrialmente, in cambio della pubblica divulgazione completa dei dettagli tecnici dell'invenzione. Per ottenerlo, l'inventore deve depositare una domanda dettagliata presso l'ufficio brevetti competente (in Italia l'UIBM, a livello europeo l'EPO), che verifica requisiti fondamentali come novità assoluta (non deve esistere nulla di identico già noto pubblicamente, ovunque nel mondo), attività inventiva (non deve essere una soluzione ovvia per un esperto del settore) e applicabilità industriale concreta. Una volta concesso, il titolare del brevetto può impedire legalmente ad altri di produrre, usare o vendere l'invenzione senza la sua autorizzazione, tipicamente concedendo licenze a pagamento a terzi interessati a sfruttarla commercialmente.$$),

(NULL, 'Perché i koala dormono così tante ore al giorno (fino a 20)?', 'Ragazzo', '👨', 'breve', 550, $$I koala si nutrono quasi esclusivamente di foglie di eucalipto, un alimento estremamente povero di valore nutritivo e calorico, oltre che leggermente tossico, che il loro corpo deve elaborare con grande cautela e dispendio energetico specifico per neutralizzarne le tossine. Con così poca energia disponibile dal cibo che mangiano, i koala hanno sviluppato una strategia di sopravvivenza basata sul risparmio energetico estremo: dormendo fino a 20 ore al giorno, riducono drasticamente il proprio metabolismo e il consumo energetico complessivo, riuscendo così a sopravvivere nonostante la dieta poverissima che altrimenti non basterebbe a sostenere un animale più attivo.$$),

(NULL, 'Come funziona il calcolo delle rate di un mutuo (tasso fisso vs variabile)?', 'Adulto', '👤', 'medio', 950, $$Un mutuo a tasso fisso mantiene lo stesso tasso di interesse (e quindi la stessa rata mensile) per tutta la durata del prestito, indipendentemente da come si muovono i tassi di mercato in futuro — offre certezza e prevedibilità, ma spesso parte con un tasso iniziale leggermente più alto rispetto a un variabile, come "premio" per quella stabilità garantita. Un mutuo a tasso variabile è invece agganciato a un indice di riferimento di mercato (in Europa tipicamente l'Euribor), che viene ricalcolato periodicamente: se i tassi di mercato scendono la rata diminuisce, se salgono la rata aumenta, esponendo chi lo sceglie a un rischio finanziario reale ma anche a un potenziale risparmio se i tassi restano bassi o scendono nel tempo. Esistono anche soluzioni intermedie, come il tasso variabile con cap (un tetto massimo oltre il quale la rata non può salire) o il tasso misto (con possibilità di passare da fisso a variabile o viceversa durante la vita del mutuo).$$),

(NULL, 'Perché le meduse pungono anche se sono morte o spiaggiate?', 'Universitario', '🎓', 'medio', 1000, $$Le meduse pungono grazie a strutture microscopiche chiamate cnidociti (o nematocisti), presenti soprattutto sui loro tentacoli, che contengono una sorta di piccolo arpione avvelenato arrotolato sotto pressione. Queste cellule urticanti si attivano tramite un meccanismo puramente meccanico e chimico — non richiedono affatto un sistema nervoso attivo o segnali coscienti dell'animale per "sparare" — semplicemente il contatto fisico con un innesco chimico appropriato (come gli oli presenti sulla pelle umana) può far scattare il meccanismo. Per questo motivo i cnidociti restano funzionanti anche per ore o giorni dopo la morte della medusa, e persino tentacoli staccati dal corpo principale (spiaggiati sulla sabbia, ad esempio) possono ancora pungere se toccati direttamente, motivo per cui è sempre sconsigliato toccare a mani nude anche meduse apparentemente morte o spiaggiate.$$),

(NULL, 'Come funziona il sistema di crediti universitari (CFU) in Italia?', 'Universitario', '🎓', 'breve', 700, $$I Crediti Formativi Universitari (CFU) sono un'unità di misura standardizzata del carico di lavoro complessivo richiesto a uno studente per superare un esame, includendo non solo le ore di lezione frontale ma anche lo studio individuale, le esercitazioni e la preparazione all'esame stesso. Convenzionalmente, un CFU corrisponde a circa 25 ore di lavoro complessivo dello studente. Un corso di laurea triennale richiede tipicamente 180 CFU complessivi (60 all'anno), mentre una laurea magistrale ne richiede altri 120. Questo sistema, adottato in tutta Europa grazie al processo di Bologna (1999), permette di confrontare e riconoscere reciprocamente i percorsi di studio tra università e paesi diversi, facilitando la mobilità studentesca internazionale (come nei programmi Erasmus).$$),

(NULL, 'Perché a volte vediamo "stelline" o lampi di luce chiudendo gli occhi e premendo le palpebre?', 'Ragazzo', '👨', 'breve', 600, $$Questo fenomeno si chiama fosfene e non ha nulla a che vedere con la luce reale: quando premi le palpebre chiuse, stai esercitando una pressione meccanica diretta sui fotorecettori della retina (le cellule che normalmente rispondono alla luce). Questi recettori sono così specializzati che possono essere attivati anche da stimoli non luminosi, come la pressione fisica o persino una scossa elettrica leggera, e il cervello interpreta comunque il loro segnale come se fosse luce reale, perché è l'unico "linguaggio" che quelle cellule sanno comunicare al cervello. Ecco perché vedi lampi e forme colorate anche se sei in una stanza completamente buia, semplicemente premendo gli occhi.$$),

(NULL, 'Come funziona il commercio equo e solidale (fair trade)?', 'Adulto', '👤', 'breve', 700, $$Il commercio equo e solidale è un modello commerciale alternativo che punta a garantire ai produttori (tipicamente agricoltori di paesi in via di sviluppo, per prodotti come caffè, cacao, banane) un prezzo minimo garantito superiore a quello di mercato tradizionale, indipendentemente dalle oscillazioni speculative dei mercati internazionali delle materie prime. Le certificazioni fair trade (come Fairtrade International) verificano che i produttori rispettino determinati standard sociali e ambientali (condizioni di lavoro dignitose, divieto di lavoro minorile, pratiche agricole sostenibili), in cambio dell'accesso a questo prezzo minimo garantito e spesso a un premio aggiuntivo destinato a investimenti collettivi nella comunità produttrice (scuole, infrastrutture). Le critiche principali al modello riguardano i costi di certificazione (che possono escludere i produttori più piccoli e poveri) e il fatto che solo una parte del sovrapprezzo pagato dal consumatore finale arriva effettivamente al produttore originario.$$),

(NULL, 'Perché i cactus riescono a sopravvivere con pochissima acqua nel deserto?', 'Bambino', '🧒', 'breve', 400, $$I cactus hanno sviluppato diversi trucchi speciali per vivere in posti dove piove pochissimo. Il loro fusto spesso e carnoso funziona come una specie di serbatoio d'acqua, immagazzinando ogni goccia di pioggia rara per usarla lentamente nei mesi successivi. Invece di avere foglie larghe (che farebbero perdere molta acqua per evaporazione), i cactus hanno spine sottilissime, che disperdono pochissima acqua e allo stesso tempo proteggono la pianta dagli animali che vorrebbero mangiarla per bere il suo prezioso liquido interno.$$),

(NULL, 'Come funziona il processo di ossidazione che fa arrugginire il ferro?', 'Universitario', '🎓', 'medio', 1000, $$La ruggine è il risultato di una reazione elettrochimica in cui il ferro metallico (Fe) reagisce con l'ossigeno atmosferico in presenza di acqua (o semplicemente umidità), formando ossido di ferro idrato (Fe₂O₃·nH₂O), il composto rossastro e friabile che chiamiamo ruggine. Il processo avviene tramite un meccanismo elettrochimico locale: in presenza di un elettrolita (come l'acqua con sali disciolti), alcune zone della superficie metallica agiscono come anodo (dove il ferro cede elettroni, ossidandosi) mentre altre zone agiscono da catodo (dove l'ossigeno viene ridotto), creando piccole celle elettrochimiche microscopiche sulla superficie del metallo. A differenza dell'ossido protettivo che si forma su metalli come l'alluminio (che crea uno strato compatto e aderente che blocca ulteriore corrosione), la ruggine è porosa e si sfalda facilmente, esponendo continuamente nuovo metallo fresco alla corrosione — questo è il motivo per cui il ferro, a differenza dell'alluminio, continua a corrodersi progressivamente fino a essere completamente consumato se non protetto (con vernici, zincatura, o leghe come l'acciaio inossidabile).$$),

(NULL, 'Perché gli struzzi non riescono a volare nonostante siano uccelli?', 'Bambino', '🧒', 'breve', 380, $$Gli struzzi hanno ali, ma sono troppo piccole rispetto al loro corpo enorme e pesante (possono pesare più di 100 chili!) per generare abbastanza portanza da sollevarli in volo. Nel corso di milioni di anni di evoluzione, gli antenati degli struzzi hanno "scambiato" la capacità di volare con una crescita enorme del corpo e gambe fortissime e velocissime, che permettono loro di correre a oltre 70 km all'ora per scappare dai predatori invece che volare via — una strategia di sopravvivenza diversa ma altrettanto efficace nel loro ambiente naturale, le savane africane aperte.$$),

(NULL, 'Come funziona il calcolo delle tasse universitarie in base all''ISEE in Italia?', 'Universitario', '🎓', 'medio', 950, $$L'ISEE (Indicatore della Situazione Economica Equivalente) è un parametro che misura la condizione economica complessiva di un nucleo familiare, combinando reddito e patrimonio (immobiliare e mobiliare) e correggendo il risultato in base al numero di componenti della famiglia tramite una scala di equivalenza standardizzata. Le università italiane utilizzano l'ISEE per calcolare le tasse universitarie in modo progressivo: famiglie con ISEE molto basso (generalmente sotto una soglia di circa 22.000-24.000 euro, variabile per ateneo) possono avere diritto all'esonero totale dalle tasse, mentre l'importo dovuto cresce gradualmente all'aumentare dell'ISEE dichiarato, fino a un tetto massimo per le fasce di reddito più alte. Questo meccanismo mira a garantire l'accesso all'istruzione universitaria indipendentemente dalla condizione economica di partenza, rendendo il costo effettivo molto variabile da famiglia a famiglia a parità di corso di laurea frequentato.$$);
