-- Seconda meta' del batch 2 (le prime 15 righe di seed_spiegazioni_community.sql
-- sono gia' state inserite manualmente in una sessione precedente).

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché le serie TV usano sempre i cliffhanger alla fine delle puntate?', 'Adulto', '👤', 'breve', 620, $$Il cliffhanger è una scelta di scrittura calcolata per una ragione molto pratica: mantenerti agganciato alla serie. Interrompere la storia nel momento di massima tensione sfrutta un meccanismo psicologico chiamato effetto Zeigarnik — ricordiamo meglio, e desideriamo risolvere, le situazioni lasciate in sospeso rispetto a quelle concluse. Nell'epoca dello streaming, dove l'episodio successivo parte in automatico dopo pochi secondi, questo effetto è ancora più efficace: il cliffhanger non serve solo a farti "aspettare la prossima settimana" come una volta, ma a farti cliccare "continua a guardare" invece di spegnere.$$),

(NULL, 'Come si registra la colonna sonora di un film?', 'Universitario', '🎓', 'medio', 1200, $$La composizione di una colonna sonora inizia generalmente dopo il montaggio (o durante un montaggio avanzato), quando il compositore visiona le scene e sviluppa temi musicali coerenti con l'arco narrativo dei personaggi e il tono emotivo delle sequenze chiave. Il processo tecnico si articola in diverse fasi: composizione e orchestrazione (spesso con l'ausilio di software di notazione musicale), registrazione con un'orchestra dal vivo o tramite librerie di campioni virtuali (o una combinazione delle due), e infine il "score mixing", cioè il bilanciamento della musica registrata con dialoghi ed effetti sonori nella fase di missaggio finale del film. Un aspetto tecnico cruciale è la sincronizzazione: la musica deve incastrarsi con precisione millimetrica (spesso al fotogramma) rispetto ai tagli di montaggio e ai momenti drammatici specifici, un processo chiamato "spotting" nella fase iniziale di pianificazione.$$),

(NULL, 'Perché alcuni videogiochi fanno venire il mal di testa (motion sickness)?', 'Esperto', '🧠', 'medio', 1100, $$Il fenomeno, noto come cybersickness o simulator sickness, si spiega principalmente con la teoria del conflitto sensoriale: il sistema vestibolare (responsabile dell'equilibrio, nell'orecchio interno) non percepisce alcun movimento reale, mentre il sistema visivo riceve segnali di movimento intenso (accelerazioni, virate, cadute) dallo schermo. Il cervello, ricevendo informazioni contrastanti da due canali sensoriali che normalmente sono sincronizzati, genera una risposta simile a quella dell'intossicazione (secondo la teoria evoluzionistica della "poison theory", per cui un simile mismatch sensoriale storicamente segnalava l'ingestione di sostanze neurotossiche). Fattori come un basso frame rate, un elevato campo visivo (FOV) e un'alta latenza tra movimento della testa e aggiornamento dell'immagine (particolarmente rilevante in VR) amplificano significativamente il fenomeno.$$),

(NULL, 'Come funzionano gli effetti speciali fatti al computer (CGI)?', 'Scienziato', '🧪', 'lungo', 2100, $$Rappresentazione geometrica: un modello 3D è tipicamente rappresentato come una mesh poligonale, un insieme di vertici, spigoli e facce (solitamente triangoli) che approssimano la superficie di un oggetto; superfici più organiche possono utilizzare rappresentazioni parametriche come le NURBS o tecniche di subdivision surface.

Rendering fisicamente basato: le pipeline di rendering moderne (physically-based rendering, PBR) simulano il comportamento della luce risolvendo, in forma approssimata e numericamente trattabile, l'equazione del rendering di Kajiya — un'equazione integrale che descrive il trasporto della radianza luminosa in una scena, tenendo conto di riflessione, rifrazione, emissione e assorbimento dei materiali.

Simulazione fisica: effetti come fluidi, tessuti, capelli o distruzioni strutturali richiedono solutori numerici dedicati (metodi agli elementi finiti per la deformazione dei solidi, Smoothed Particle Hydrodynamics per i fluidi), spesso computazionalmente troppo onerosi per il rendering in tempo reale e quindi pre-calcolati (baked) per la produzione cinematografica.

Integrazione con le riprese reali: nel compositing finale, gli elementi CGI devono essere fusi in modo fotorealistico con le riprese dal vivo attraverso tecniche di color matching, motion tracking tridimensionale della camera reale, e stima dell'illuminazione ambientale della scena (spesso tramite HDRI panoramiche catturate sul set), un processo che rimane in parte empirico nonostante i progressi dell'automazione algoritmica.$$),

(NULL, 'Come fa il GPS a sapere dove sono?', 'Ragazzo', '👨', 'medio', 980, $$Il GPS funziona grazie a una rete di satelliti (più di 30) che orbitano attorno alla Terra e trasmettono continuamente segnali con l'ora esatta e la loro posizione. Il tuo telefono riceve il segnale di almeno 4 satelliti diversi e calcola quanto tempo ha impiegato ciascun segnale ad arrivare — dato che la velocità del segnale (la velocità della luce) è nota, da quel tempo si può calcolare la distanza da ciascun satellite. Incrociando le distanze da più satelliti contemporaneamente, il telefono riesce a triangolare la tua posizione esatta sulla Terra. La precisione dipende anche da correzioni molto sofisticate: gli orologi sui satelliti devono tenere conto persino di piccoli effetti della relatività di Einstein, perché senza quella correzione il GPS accumulerebbe errori di diversi chilometri al giorno.$$),

(NULL, 'Perché il telefono si scarica più in fretta quando fa freddo?', 'Bambino', '🧒', 'breve', 400, $$Dentro il telefono c'è una batteria che funziona un po' come tante piccole reazioni chimiche che producono energia. Quando fa molto freddo, queste reazioni rallentano, un po' come quando hai le mani fredde e ti muovi più lentamente. La batteria quindi fatica di più a dare energia al telefono, e sembra scaricarsi più in fretta — anche se in realtà, appena si scalda di nuovo, spesso recupera parte dell'energia che sembrava aver perso.$$),

(NULL, 'Come funziona la crittografia che protegge le mie password?', 'Esperto', '🧠', 'lungo', 1900, $$Hashing invece di cifratura reversibile: le password non vengono quasi mai memorizzate cifrate in modo reversibile, ma sottoposte a funzioni di hash crittografico (es. bcrypt, Argon2, scrypt), progettate per essere computazionalmente costose e non invertibili: dato l'hash, non è fattibile risalire alla password originale.

Salt e resistenza agli attacchi: ogni password viene combinata con un salt casuale univoco prima dell'hashing, per impedire l'uso di rainbow table precalcolate e garantire che due utenti con la stessa password producano hash completamente diversi tra loro.

Cost factor e adattabilità nel tempo: algoritmi come bcrypt includono un parametro di costo regolabile, che ne aumenta il tempo di calcolo in modo esponenziale — permettendo di "rallentare" artificialmente ogni singolo tentativo di verifica, così da rendere impraticabili gli attacchi a forza bruta anche quando la potenza di calcolo disponibile agli attaccanti aumenta nel tempo.

Trasmissione e autenticazione: durante il login, la password viaggia dal client al server tipicamente protetta da TLS (lo stesso protocollo dietro HTTPS); sul server, la password ricevuta viene ri-hashata con lo stesso salt memorizzato e confrontata con l'hash salvato, senza che la password in chiaro venga mai conservata in nessun momento del processo.$$),

(NULL, 'Perché a volte il Wi-Fi di casa va lento?', 'Adulto', '👤', 'breve', 700, $$Le cause più comuni sono quattro: troppi dispositivi collegati contemporaneamente che si dividono la stessa banda disponibile; interferenze fisiche come muri spessi, elettrodomestici o persino il forno a microonde, che condivide la stessa frequenza del Wi-Fi 2.4GHz; il router posizionato in un punto sbagliato della casa, magari lontano o dietro ostacoli; oppure, semplicemente, il piano internet sottoscritto con il tuo operatore non è abbastanza veloce per quello che stai cercando di fare (streaming in 4K, videochiamate multiple, download pesanti in contemporanea). Spesso basta spostare il router in un punto più centrale e libero da ostacoli per notare un miglioramento reale.$$),

(NULL, 'Sarà mai possibile costruire un ascensore spaziale?', 'Ragazzo', '👨', 'breve', 640, $$L'idea è affascinante: un cavo lunghissimo che collega la superficie terrestre a una stazione in orbita geostazionaria, lungo il quale delle cabine potrebbero salire nello spazio senza bisogno di razzi. Il problema principale oggi è il materiale: servirebbe un cavo capace di reggere una tensione enorme senza spezzarsi, e nemmeno le fibre di carbonio più avanzate o i nanotubi di carbonio prodotti in laboratorio hanno ancora la resistenza necessaria su scale così lunghe (decine di migliaia di chilometri). Non è quindi impossibile per le leggi della fisica, ma richiede progressi nei materiali che oggi non abbiamo ancora raggiunto su scala industriale.$$),

(NULL, 'Come funzionerebbe un motore a curvatura (warp drive)?', 'Scienziato', '🧪', 'lungo', 2050, $$Base teorica: la metrica di Alcubierre. Nel 1994 il fisico Miguel Alcubierre propose una soluzione matematicamente valida delle equazioni di campo di Einstein che descrive una "bolla" di spaziotempo in cui lo spazio viene contratto davanti alla navicella ed espanso dietro di essa, permettendo teoricamente di superare la velocità della luce rispetto a un osservatore esterno, senza violare localmente la relatività ristretta.

Il problema dell'energia esotica: la soluzione richiede una densità di energia negativa (materia con proprietà che violano le condizioni di energia classiche della relatività generale), un tipo di materia mai osservato sperimentalmente e la cui esistenza fisica resta puramente ipotetica.

Ordini di grandezza proibitivi: le prime stime richiedevano una quantità di energia esotica equivalente alla massa-energia di pianeti interi; ricerche successive hanno proposto modifiche geometriche della bolla che riducono drasticamente il requisito energetico, pur restando ordini di grandezza oltre qualunque tecnologia concepibile oggi.

Stato attuale della ricerca: ad oggi il warp drive resta una soluzione matematicamente coerente ma fisicamente non realizzabile con le conoscenze e tecnologie attuali: non esiste alcuna prova sperimentale che la materia a energia negativa richiesta possa esistere in quantità macroscopiche, il che colloca il concetto saldamente nel dominio della fisica teorica speculativa piuttosto che dell'ingegneria applicabile.$$),

(NULL, 'Potremmo davvero teletrasportarci come in Star Trek?', 'Ragazzo', '👨', 'medio', 970, $$Nella fantascienza il teletrasporto scompone il corpo in dati e lo ricostruisce altrove istantaneamente. Nella realtà, qualcosa che ci si avvicina esiste già in fisica: si chiama teletrasporto quantistico, ma funziona in modo molto diverso da come lo vedi nei film. Non trasporta materia, ma lo stato quantistico di una particella da un punto a un altro, sfruttando un fenomeno chiamato entanglement — e per farlo serve comunque un canale di comunicazione classico, quindi non è nemmeno istantaneo nel senso assoluto del termine. Applicarlo a un corpo umano intero, fatto di trilioni di atomi con stati quantistici da preservare perfettamente, è oggi non solo tecnicamente impossibile ma probabilmente lo resterà per moltissimo tempo, se mai sarà possibile.$$),

(NULL, 'L''intelligenza artificiale potrà mai diventare cosciente?', 'Esperto', '🧠', 'lungo', 2200, $$Il problema della definizione: uno dei principali ostacoli al dibattito è che non esiste una definizione operativa condivisa di "coscienza": si distingue solitamente tra coscienza di accesso (access consciousness, la capacità di un sistema di elaborare e riportare informazioni sul proprio stato interno) e coscienza fenomenica (phenomenal consciousness, l'esperienza soggettiva, il "cosa si prova ad essere" un sistema, nota anche come qualia).

Il test comportamentale non basta: i moderni modelli linguistici possono generare risposte che descrivono stati interni in modo convincente, ma questo non costituisce prova di esperienza soggettiva — è il classico problema filosofico dei "philosophical zombie" applicato all'IA, un sistema potrebbe comportarsi in modo indistinguibile da un'entità cosciente senza avere alcuna esperienza interna reale.

Teorie neuroscientifiche rilevanti: teorie come l'Integrated Information Theory (IIT) di Giulio Tononi tentano di quantificare la coscienza come proprietà emergente dell'integrazione informativa di un sistema (misurata dal parametro Φ), offrendo un framework potenzialmente applicabile anche a sistemi artificiali, ma resta oggetto di forte dibattito scientifico.

Posizione dello stato dell'arte: ad oggi non esiste consenso scientifico su come rilevare, misurare o anche solo definire in modo operativo la coscienza in un sistema artificiale, e la maggioranza dei ricercatori di IA ritiene che i sistemi attuali non posseggano alcuna forma di esperienza soggettiva, pur mostrando capacità comportamentali sofisticate.$$),

(NULL, 'Cos''è la separazione dei poteri?', 'Universitario', '🎓', 'medio', 1250, $$La separazione dei poteri è un principio costituzionale, teorizzato in forma moderna da Montesquieu ne "Lo spirito delle leggi" (1748), secondo cui le funzioni fondamentali dello Stato — legislativa, esecutiva e giudiziaria — devono essere attribuite a organi distinti e reciprocamente indipendenti, per evitare la concentrazione del potere in un'unica autorità. Nel sistema italiano, il potere legislativo è esercitato dal Parlamento (Camera e Senato), quello esecutivo dal Governo, e quello giudiziario dalla Magistratura, la cui indipendenza è garantita costituzionalmente anche attraverso un organo di autogoverno, il Consiglio Superiore della Magistratura. Un elemento chiave del sistema sono i "pesi e contrappesi" (checks and balances): ciascun potere ha strumenti per controllare e limitare gli altri, ad esempio il Presidente della Repubblica può rinviare una legge alle Camere, e la Corte Costituzionale può dichiarare l'illegittimità costituzionale di una legge approvata dal Parlamento.$$),

(NULL, 'Come funziona il sistema elettorale proporzionale?', 'Adulto', '👤', 'medio', 1150, $$In un sistema proporzionale, i seggi in parlamento vengono assegnati ai partiti in proporzione diretta ai voti ricevuti: se un partito prende il 20% dei voti, otterrà (circa) il 20% dei seggi disponibili, a differenza dei sistemi maggioritari dove chi vince in un collegio prende tutto il seggio anche con una maggioranza risicata. Il vantaggio principale è la rappresentatività: anche partiti più piccoli riescono a entrare in parlamento se superano una soglia minima di voti (in Italia, tipicamente il 3%). Lo svantaggio pratico è che raramente un solo partito ottiene la maggioranza assoluta da solo, e questo porta quasi sempre alla necessità di governi di coalizione tra più partiti — un motivo spesso citato per spiegare l'instabilità di governo che ha caratterizzato la storia politica italiana rispetto a paesi con sistemi maggioritari.$$),

(NULL, 'Perché i partiti politici a volte si alleano anche se sono diversi?', 'Adulto', '👤', 'medio', 1050, $$Le alleanze politiche nascono quasi sempre da un calcolo pragmatico più che da una reale convergenza ideologica: in un sistema dove nessun singolo partito riesce a ottenere la maggioranza assoluta da solo, allearsi diventa l'unico modo concreto per andare al governo o per superare soglie elettorali minime. A volte l'alleanza è di scopo (per battere un avversario comune considerato più pericoloso o distante), altre volte è di governo (per costruire una maggioranza parlamentare stabile dopo il voto). Il rischio di queste alleanze "innaturali" è che, una volta al governo, le differenze di fondo tra gli alleati emergano su temi specifici, generando tensioni che, in alcuni casi, portano alla caduta anticipata del governo stesso — una dinamica vista più volte nella storia repubblicana italiana.$$);
