-- Batch 12: chiusura ampliamento a 100 nuove spiegazioni mainstream.

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché il latte scremato ha meno calorie di quello intero?', 'Bambino', '🧒', 'breve', 380, $$Il latte contiene naturalmente dei grassi, e i grassi sono la parte del cibo che porta più energia (calorie) in assoluto rispetto a proteine e zuccheri, a parità di peso. Il latte scremato viene lavorato apposta per togliere gran parte di questi grassi, lasciando quasi solo acqua, proteine e zuccheri del latte — per questo ha molte meno calorie del latte intero, dove i grassi sono ancora tutti presenti.$$),

(NULL, 'Come funziona il processo di raffinazione del petrolio in benzina e altri prodotti?', 'Universitario', '🎓', 'medio', 1150, $$Il petrolio grezzo estratto dai giacimenti è una miscela complessa di migliaia di composti idrocarburici diversi, non direttamente utilizzabile. La raffineria lo separa attraverso un processo chiamato distillazione frazionata: il petrolio viene riscaldato ad alta temperatura in una colonna di distillazione, dove i diversi componenti evaporano e poi ricondensano a temperature diverse in base al loro punto di ebollizione specifico, che dipende dal peso molecolare di ciascun composto. I componenti più leggeri (come i gas e la benzina) condensano nella parte alta e più fredda della colonna, mentre quelli più pesanti (come il gasolio, gli oli lubrificanti e il bitume) si raccolgono verso il basso, dove la temperatura resta più alta. Le raffinerie moderne applicano poi processi aggiuntivi (cracking catalitico, reforming) per trasformare i componenti più pesanti e meno richiesti dal mercato in prodotti più leggeri e preziosi, come la benzina, ottimizzando la resa economica di ogni barile di greggio lavorato.$$),

(NULL, 'Perché a volte ci prude la pelle senza un motivo apparente?', 'Adulto', '👤', 'breve', 650, $$Il prurito senza causa apparente ha diverse possibili spiegazioni fisiologiche comuni: la pelle secca (xerosi), particolarmente frequente in inverno o con l'invecchiamento, che indebolisce la barriera cutanea protettiva ed espone le terminazioni nervose a maggiore sensibilità; reazioni allergiche lievi a fattori ambientali (polvere, tessuti, detergenti) troppo deboli per causare sintomi visibili come arrossamento; o semplicemente fluttuazioni ormonali e vascolari che aumentano la sensibilità nervosa della pelle in modo transitorio. Un prurito persistente, diffuso e senza causa apparente identificabile può occasionalmente essere anche un segnale di condizioni sistemiche sottostanti (problemi tiroidei, renali o epatici), motivo per cui un prurito cronico e inspiegabile che dura settimane merita una valutazione medica invece di essere ignorato.$$),

(NULL, 'Come funziona il processo di fermentazione della birra?', 'Universitario', '🎓', 'medio', 1100, $$La produzione della birra inizia con il maltaggio dell'orzo (o altri cereali), un processo che fa germinare parzialmente i chicchi per attivare enzimi capaci di convertire l'amido in zuccheri fermentabili. Il malto viene poi macinato e mescolato con acqua calda in un processo chiamato ammostamento, dove gli enzimi completano la conversione dell'amido in zuccheri semplici (soprattutto maltosio), producendo un liquido dolce chiamato mosto. Il mosto viene bollito insieme al luppolo (che conferisce amaro, aroma e proprietà conservanti) e poi raffreddato per l'aggiunta del lievito, l'organismo responsabile della vera e propria fermentazione: il lievito metabolizza gli zuccheri del mosto producendo alcol etilico e anidride carbonica come prodotti di scarto del proprio metabolismo. Il tipo di lievito usato (a fermentazione alta, come nelle ale, o a fermentazione bassa e a temperature più fredde, come nelle lager) determina in gran parte il profilo aromatico e lo stile finale della birra prodotta.$$),

(NULL, 'Perché il nostro corpo produce colesterolo se fa male alla salute?', 'Universitario', '🎓', 'medio', 1050, $$Il colesterolo non è affatto una sostanza intrinsecamente dannosa: è un componente essenziale delle membrane cellulari di ogni cellula del corpo, ed è il precursore biochimico necessario per produrre ormoni steroidei fondamentali (come testosterone, estrogeni e cortisolo), vitamina D e acidi biliari indispensabili per digerire i grassi. Il fegato produce naturalmente la maggior parte del colesterolo di cui il corpo ha bisogno, indipendentemente dalla dieta. Il problema per la salute cardiovascolare non riguarda il colesterolo in sé, ma il suo eccesso circolante nel sangue — in particolare l'eccesso della lipoproteina LDL (spesso chiamata impropriamente "colesterolo cattivo") — che può depositarsi progressivamente sulle pareti arteriose formando placche che restringono i vasi sanguigni (aterosclerosi), aumentando il rischio di infarto e ictus nel lungo periodo, specialmente in combinazione con altri fattori di rischio come fumo, ipertensione o diabete.$$),

(NULL, 'Come fanno i coralli a costruire le barriere coralline?', 'Ragazzo', '👨', 'medio', 850, $$I coralli non sono piante, come molti pensano, ma piccolissimi animali (polipi) che vivono in enormi colonie, geneticamente identiche tra loro, formatesi per riproduzione asessuata ripetuta a partire da un unico polipo fondatore. Ogni singolo polipo corallino costruisce intorno a sé un piccolo scheletro rigido di carbonato di calcio estratto dall'acqua di mare, e quando muore il suo scheletro resta come base su cui i polipi successivi costruiscono il proprio, strato dopo strato, nel corso di migliaia di anni. Una barriera corallina come la Grande Barriera Corallina australiana è quindi in pratica una struttura geologica vivente, costruita progressivamente da miliardi di questi minuscoli scheletri accumulati nel tempo, non una singola gigantesca creatura.$$),

(NULL, 'Perché quando togliamo un cerotto velocemente fa comunque un po'' male?', 'Bambino', '🧒', 'breve', 380, $$Il cerotto è appiccicato non solo alla superficie della pelle, ma anche ai piccoli peli che crescono sulla tua pelle, quasi invisibili a occhio nudo. Quando strappi il cerotto velocemente, stai in realtà strappando anche questi piccoli peli tutti insieme in un istante, un po' come una piccola ceretta veloce. Il dolore che senti viene proprio da lì, non tanto dalla pelle stessa: ecco perché anche togliendolo di scatto senti comunque un piccolo fastidio improvviso.$$),

(NULL, 'Come funziona un sistema di riconoscimento vocale come Alexa o Siri?', 'Esperto', '🧠', 'medio', 1050, $$Gli assistenti vocali moderni utilizzano una pipeline in più fasi: prima un modello dedicato di rilevamento della parola chiave ("wake word", come "Alexa" o "Hey Siri") monitora continuamente l'audio localmente sul dispositivo, con basso consumo energetico, per attivare il sistema solo quando riconosce quella specifica sequenza sonora. Una volta attivato, l'audio successivo viene inviato (o elaborato localmente nei sistemi più recenti orientati alla privacy) a un modello di riconoscimento vocale automatico (ASR) che trascrive il parlato in testo. Il testo trascritto viene poi analizzato da un modulo di comprensione del linguaggio naturale (NLU), che identifica l'intento dell'utente (es. "imposta un timer", "che tempo fa") e i parametri rilevanti (durata del timer, città per il meteo), instradando la richiesta al servizio appropriato che genera una risposta, infine convertita di nuovo in voce tramite un sistema di sintesi vocale (text-to-speech) prima di essere restituita all'utente.$$),

(NULL, 'Perché il vino rosso viene servito a temperatura ambiente e il bianco freddo?', 'Adulto', '👤', 'breve', 700, $$La temperatura di servizio influenza direttamente la percezione sensoriale di aromi, tannini e acidità del vino. I vini rossi contengono tipicamente più tannini (composti che danno la sensazione di astringenza "che asciuga la bocca"), e temperature più alte (16-18°C) ammorbidiscono percettivamente questi tannini e liberano più pienamente gli aromi complessi tipici dei rossi strutturati; servirli troppo freddi li renderebbe eccessivamente aspri e chiusi aromaticamente. I vini bianchi, generalmente più freschi, acidi e con profili aromatici più delicati e fruttati, vengono invece serviti freddi (8-12°C) perché il freddo esalta la percezione di freschezza e acidità bilanciata, mentre temperature troppo alte li renderebbero piatti e farebbero emergere eccessivamente l'alcol a scapito della delicatezza aromatica.$$),

(NULL, 'Come funziona il fenomeno dell''arcobaleno lunare (raro e visibile di notte)?', 'Universitario', '🎓', 'medio', 950, $$L'arcobaleno lunare (o "moonbow") si forma esattamente con lo stesso principio fisico di un arcobaleno solare — rifrazione, riflessione interna e dispersione della luce attraverso goccioline d'acqua sospese nell'aria — ma usando la luce riflessa dalla Luna invece che quella diretta del Sole. Poiché la luce lunare è enormemente più debole (la Luna riflette solo una piccola frazione della luce solare che riceve), l'arcobaleno lunare risultante è molto meno intenso e i suoi colori sono spesso impercettibili all'occhio umano, che a basse intensità luminose perde gran parte della sensibilità ai colori (percependo prevalentemente in scala di grigi tramite i bastoncelli retinici anziché i coni sensibili al colore) — fotografie a lunga esposizione, che accumulano più luce nel tempo, riescono invece a catturare e rivelare i colori reali dell'arcobaleno lunare, altrimenti quasi invisibili a occhio nudo.$$),

(NULL, 'Perché i cani annusano così tanto quando fanno una passeggiata?', 'Bambino', '🧒', 'breve', 380, $$Il naso di un cane è incredibilmente più potente del nostro: ha centinaia di milioni di recettori olfattivi in più rispetto al naso umano, ed è capace di distinguere odori mille volte più deboli di quanto riusciamo a percepire noi. Per un cane, annusare durante una passeggiata è un po' come per noi leggere il giornale o guardare i social media: ogni odore gli racconta una storia — quali altri animali sono passati di lì, quando, se erano maschi o femmine, se erano spaventati o tranquilli. Per questo motivo, lasciare che un cane annusi con calma durante la passeggiata è importante per il suo benessere mentale, non è solo un capriccio.$$),

(NULL, 'Come funziona il calcolo dell''affitto equo/calmierato in alcune città?', 'Adulto', '👤', 'breve', 700, $$I sistemi di calmieramento degli affitti (rent control) limitano legalmente quanto un proprietario può aumentare l'affitto di un immobile, tipicamente agganciando gli aumenti consentiti a un indice ufficiale (come l'inflazione) invece che lasciarli liberi al mercato. L'obiettivo dichiarato è proteggere gli inquilini esistenti da aumenti improvvisi e insostenibili, specialmente in città con forte pressione abitativa e prezzi in rapida crescita. Gli economisti restano divisi sull'efficacia di lungo periodo di queste politiche: alcuni studi indicano che il calmieramento riduce effettivamente la volatilità degli affitti per chi già vive in un immobile regolamentato, ma altri sottolineano effetti collaterali negativi, come la riduzione degli investimenti privati in nuove costruzioni o manutenzioni (meno redditizie sotto controllo dei prezzi) e una minore disponibilità complessiva di alloggi in affitto nel lungo periodo, con potenziale beneficio concentrato su chi già occupa un immobile regolamentato a scapito di chi cerca casa per la prima volta.$$),

(NULL, 'Perché le vespe sono più aggressive delle api?', 'Ragazzo', '👨', 'breve', 600, $$Le api generalmente pungono solo come ultima difesa, perché il loro pungiglione seghettato resta conficcato nella pelle della vittima e si strappa dal corpo dell'ape quando questa cerca di volare via, causandole la morte — pungere è quindi un sacrificio finale per l'ape, non una scelta fatta a cuor leggero. Le vespe, invece, hanno un pungiglione liscio che possono estrarre e riutilizzare più volte senza conseguenze per sé stesse, il che le rende molto più propense a pungere ripetutamente per difendere il nido o semplicemente per allontanare una minaccia percepita, senza il "costo" fatale che l'atto comporta per un'ape. Inoltre alcune specie di vespe sono predatrici attive (cacciano altri insetti) e tendenzialmente più territoriali e reattive rispetto alle api, generalmente più concentrate sulla raccolta di nettare e polline.$$),

(NULL, 'Come funziona il processo con cui le banche creano moneta prestando denaro?', 'Esperto', '🧠', 'medio', 1150, $$Nel sistema bancario a riserva frazionaria, le banche commerciali non prestano semplicemente il denaro depositato dai risparmiatori: quando una banca concede un prestito, crea contabilmente nuovo denaro sotto forma di deposito nel conto del beneficiario, obbligata a mantenere solo una frazione di quella somma come riserva (in contanti o presso la banca centrale), non l'intero importo. Questo processo, chiamato moltiplicatore monetario, significa che l'ammontare totale di moneta in circolazione nell'economia è significativamente superiore alla base monetaria fisica effettivamente creata dalla banca centrale — ogni prestito genera nuovi depositi, che a loro volta possono essere in parte riprestati da altre banche, moltiplicando l'effetto complessivo. Le banche centrali regolano questo processo attraverso requisiti di riserva obbligatoria e tassi di interesse, strumenti chiave della politica monetaria per controllare la quantità di credito e moneta disponibile nell'economia complessiva.$$),

(NULL, 'Perché le nuvole restano sospese in aria anche se sono fatte di acqua, che è pesante?', 'Ragazzo', '👨', 'medio', 750, $$Le nuvole sono fatte di goccioline d'acqua (o cristalli di ghiaccio) incredibilmente piccole, con un diametro tipico di appena 10-15 micrometri — così minuscole e leggere che la resistenza dell'aria (attrito) che incontrano cadendo è sufficiente a controbilanciare quasi completamente la forza di gravità che le tira verso il basso, facendole scendere a una velocità praticamente impercettibile, quasi come se galleggiassero. Inoltre, le correnti d'aria ascendenti presenti all'interno e intorno alla nuvola stessa spesso contrastano ulteriormente questa lentissima caduta, mantenendo la nuvola visivamente "sospesa" per lungo tempo. Quando le goccioline si aggregano tra loro diventando abbastanza grandi e pesanti da superare questa resistenza dell'aria, cadono più velocemente verso il suolo: è esattamente in quel momento che si genera la pioggia.$$),

(NULL, 'Come funziona il sistema di quote rosa (parità di genere) nelle liste elettorali italiane?', 'Universitario', '🎓', 'medio', 950, $$Le cosiddette "quote di genere" nelle liste elettorali italiane, introdotte progressivamente da diverse leggi elettorali a partire dagli anni 2010, impongono vincoli minimi sulla rappresentanza di ciascun genere nelle candidature, con l'obiettivo dichiarato di correggere lo squilibrio storico nella rappresentanza politica femminile. Le modalità tecniche variano a seconda della legge elettorale specifica in vigore: possono riguardare la composizione complessiva delle liste (nessun genere può superare una certa percentuale massima, tipicamente il 60%), oppure l'alternanza obbligatoria di genere nell'ordine di lista (il cosiddetto meccanismo "a cerniera", dove uomini e donne si alternano posizione per posizione). L'efficacia effettiva di questi meccanismi nel tradursi in una rappresentanza parlamentare realmente equilibrata dipende molto dai dettagli tecnici specifici della legge elettorale applicata, in particolare da come vengono gestite le preferenze espresse dagli elettori e l'ordine effettivo di elezione dei candidati.$$),

(NULL, 'Perché a volte perdiamo l''equilibrio se chiudiamo gli occhi stando in piedi su una gamba sola?', 'Adulto', '👤', 'breve', 650, $$Mantenere l'equilibrio richiede l'integrazione continua di tre sistemi sensoriali principali: il sistema vestibolare nell'orecchio interno (che rileva accelerazioni e rotazioni della testa), la propriocezione (i recettori nei muscoli e nelle articolazioni che informano il cervello sulla posizione delle diverse parti del corpo), e la vista, che fornisce un riferimento visivo stabile dell'ambiente circostante fondamentale per correggere continuamente piccole oscillazioni posturali. Chiudendo gli occhi mentre si sta già in equilibrio precario su una gamba sola, il cervello perde improvvisamente uno dei tre canali sensoriali principali su cui faceva affidamento, dovendo compensare esclusivamente con vestibolare e propriocezione — per molte persone, soprattutto se non allenate specificamente all'equilibrio (come ballerini o praticanti di yoga), questa perdita improvvisa di informazione visiva rende molto più difficile correggere in tempo le piccole oscillazioni naturali del corpo, portando a una perdita di equilibrio evidente e quasi immediata.$$),

(NULL, 'Come funziona il calcolo del punto di pareggio (break-even point) in un''azienda?', 'Adulto', '👤', 'medio', 850, $$Il punto di pareggio è il livello di fatturato (o di unità vendute) al quale i ricavi totali di un'azienda eguagliano esattamente i costi totali, senza generare né profitto né perdita. Per calcolarlo, i costi vengono divisi in due categorie: costi fissi (che restano costanti indipendentemente dal volume di produzione o vendita, come affitto, stipendi fissi, assicurazioni) e costi variabili (che aumentano proporzionalmente al volume di attività, come materie prime o commissioni di vendita). La formula base divide i costi fissi totali per il "margine di contribuzione unitario" (il prezzo di vendita di un'unità meno il costo variabile di produrla), ottenendo il numero minimo di unità che devono essere vendute per coprire tutti i costi fissi. Conoscere questo valore è fondamentale per un'azienda per capire quale volume minimo di attività è necessario prima di iniziare a generare un profitto reale, e per valutare la sostenibilità economica di un nuovo prodotto o progetto prima ancora di lanciarlo sul mercato.$$),

(NULL, 'Perché il bambù cresce così velocemente rispetto ad altre piante?', 'Ragazzo', '👨', 'medio', 700, $$Il bambù, che tecnicamente è una gigantesca erba e non un albero vero e proprio, può crescere anche di quasi un metro al giorno in condizioni ottimali — tra le piante più veloci al mondo in assoluto. Questa crescita straordinaria è possibile perché il bambù non deve costruire nuova struttura legnosa dal nulla ogni volta come farebbe un albero: la pianta possiede già, sottoterra, tutti i segmenti (internodi) del futuro fusto pre-formati e compressi come una fisarmonica chiusa. Quando le condizioni sono giuste (acqua, temperatura, luce), la pianta non deve far altro che "espandere" ed estendere rapidamente questi segmenti già pronti, invece di doverli costruire cellula per cellula partendo da zero — un po' come aprire velocemente una fisarmonica già montata, invece di doverla costruire pezzo per pezzo.$$),

(NULL, 'Come funziona il meccanismo con cui i vaccini a mRNA (come quelli anti-COVID) istruiscono le cellule?', 'Scienziato', '🧪', 'lungo', 2000, $$Struttura e stabilità dell'mRNA: i vaccini a mRNA veicolano una sequenza sintetica di RNA messaggero, modificata chimicamente (tipicamente tramite sostituzione della uridina con pseudouridina) per ridurre il riconoscimento come materiale estraneo da parte dei sensori immunitari innati della cellula e aumentarne la stabilità e l'efficienza di traduzione.

Veicolazione tramite nanoparticelle lipidiche: poiché l'RNA nudo verrebbe rapidamente degradato da enzimi (RNasi) presenti nei fluidi corporei e non attraverserebbe efficacemente la membrana cellulare, viene incapsulato in nanoparticelle lipidiche (LNP), piccole sfere di lipidi che proteggono l'mRNA e facilitano la sua fusione con la membrana cellulare per il rilascio del contenuto nel citoplasma.

Traduzione e presentazione antigenica: una volta nel citoplasma, i ribosomi della cellula ospite leggono la sequenza di mRNA e sintetizzano la proteina codificata (nel caso dei vaccini COVID-19, la proteina Spike virale, o solo una sua porzione). Frammenti di questa proteina vengono presentati sulla superficie cellulare tramite molecole MHC, permettendo al sistema immunitario di riconoscerli come estranei e montare una risposta immunitaria specifica, comprensiva di anticorpi neutralizzanti e memoria immunitaria a lungo termine, senza che il virus reale sia mai stato introdotto nell'organismo.

Degradazione e sicurezza: l'mRNA sintetico introdotto ha un'emivita relativamente breve (viene degradato dai normali meccanismi cellulari nel giro di ore o pochi giorni) e, essendo tradotto nel citoplasma senza mai entrare nel nucleo cellulare, non ha alcuna possibilità di integrarsi nel DNA genomico dell'ospite, una preoccupazione frequentemente sollevata ma non supportata dal meccanismo biologico reale di funzionamento di questa tecnologia.$$);
