-- Batch 6: ampliamento community spiegazioni (astronomia, corpo umano,
-- economia quotidiana, tecnologia, natura).

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché le stelle sembrano scintillare mentre i pianeti no?', 'Ragazzo', '👨', 'medio', 750, $$Le stelle sono così lontane che, anche viste dai telescopi più potenti, appaiono come singoli punti di luce senza dimensione apparente. Quando la loro luce attraversa l'atmosfera terrestre, incontra strati d'aria a temperature e densità diverse in continuo movimento, che deviano leggermente il raggio di luce in modo imprevedibile — questo crea l'effetto di "scintillio" (tremolio) che vediamo. I pianeti, invece, pur essendo anch'essi lontanissimi, appaiono come piccoli dischi (non punti) perché sono molto più vicini della maggior parte delle stelle: la luce che arriva da un disco più ampio viene mediata su più raggi leggermente diversi, che si compensano a vicenda e riducono di molto l'effetto di tremolio.$$),

(NULL, 'Come fa il corpo a sapere quando è ora di avere fame?', 'Universitario', '🎓', 'medio', 1100, $$La regolazione della fame coinvolge un sistema complesso di segnali ormonali che comunicano con l'ipotalamo, la regione cerebrale che integra questi segnali in una sensazione conscia di fame o sazietà. La grelina, prodotta principalmente dallo stomaco quando è vuoto, agisce come segnale "accendi la fame" e i suoi livelli aumentano prima dei pasti abituali, seguendo un ritmo appreso dal corpo. Al contrario, ormoni come la leptina (prodotta dal tessuto adiposo, segnala le riserve di energia a lungo termine) e il peptide YY (rilasciato dall'intestino dopo un pasto) inviano segnali di sazietà. Questo sistema, tuttavia, può essere disregolato da fattori come il sonno insufficiente (che altera l'equilibrio grelina/leptina aumentando la fame) o lo stress cronico, spiegando perché la fame non è sempre un indicatore affidabile del reale bisogno energetico del corpo.$$),

(NULL, 'Perché conviene diversificare gli investimenti invece di puntare tutto su un solo titolo?', 'Adulto', '👤', 'medio', 950, $$La diversificazione riduce il rischio specifico (legato a una singola azienda o settore) senza necessariamente ridurre il rendimento atteso nel lungo periodo, sfruttando il fatto che i rendimenti di asset diversi non sono perfettamente correlati tra loro: quando un settore va male, un altro spesso compensa. Concretamente, se investi tutto in un'unica azienda e questa fallisce o attraversa una crisi (anche per motivi imprevedibili, come uno scandalo o un cambio normativo), perdi una parte significativa del capitale; distribuendo lo stesso capitale su decine o centinaia di titoli diversi (ad esempio tramite un fondo indicizzato), il fallimento di una singola azienda ha un impatto marginale sul portafoglio complessivo. Questo principio, formalizzato dalla teoria del portafoglio di Harry Markowitz (Nobel per l'economia 1990), non elimina il rischio di mercato generale, ma riduce drasticamente quello "eliminabile" legato a singole scelte specifiche.$$),

(NULL, 'Come fanno i pipistrelli a volare al buio senza sbattere contro le cose?', 'Bambino', '🧒', 'breve', 400, $$I pipistrelli emettono suoni acutissimi, troppo alti per essere sentiti dalle nostre orecchie, e poi ascoltano l'eco che torna indietro quando quei suoni rimbalzano sugli oggetti intorno a loro. In pratica "vedono" con le orecchie invece che con gli occhi! Questa tecnica si chiama ecolocalizzazione, e permette loro di capire con precisione dove si trovano gli alberi, i muri o perfino piccolissimi insetti da cacciare, anche nella totale oscurità della notte.$$),

(NULL, 'Perché conviene avere un fondo di emergenza prima di investire?', 'Adulto', '👤', 'breve', 650, $$Un fondo di emergenza (di solito l'equivalente di 3-6 mesi di spese essenziali, tenuto liquido e facilmente accessibile) serve a evitare di dover vendere investimenti nel momento sbagliato in caso di imprevisti — una spesa medica urgente, la perdita del lavoro, una riparazione importante. Senza questo cuscinetto, un imprevisto ti costringerebbe a liquidare investimenti magari proprio quando il mercato è in ribasso, trasformando una perdita solo "sulla carta" (temporanea) in una perdita reale e definitiva. Avere prima questa riserva ti permette anche di investire con un orizzonte temporale più lungo e con meno ansia, perché sai che gli imprevisti a breve termine sono già coperti separatamente.$$),

(NULL, 'Come funziona il riciclo della plastica?', 'Ragazzo', '👨', 'medio', 900, $$Il riciclo della plastica inizia con la raccolta differenziata, seguita da una fase di selezione (spesso automatizzata con sensori ottici) che separa i diversi tipi di plastica in base al codice di resina indicato dal triangolino con il numero sulla confezione — non tutte le plastiche sono compatibili tra loro nel processo di riciclo. La plastica selezionata viene lavata, triturata in scaglie, e poi fusa per essere trasformata in nuovi granuli di materia prima, pronti per produrre nuovi oggetti. Un limite importante: la maggior parte delle plastiche perde qualità ad ogni ciclo di riciclo (downcycling), quindi raramente una bottiglia riciclata diventa di nuovo una bottiglia identica — più spesso diventa un prodotto di qualità inferiore, come tessuti sintetici o imbottiture. Per questo la riduzione del consumo di plastica resta più efficace del solo riciclo nel ridurre l'impatto ambientale complessivo.$$),

(NULL, 'Perché la pressione sanguigna si misura con due numeri (tipo 120/80)?', 'Universitario', '🎓', 'medio', 1000, $$I due numeri della pressione arteriosa rappresentano due fasi distinte del ciclo cardiaco. Il primo numero (pressione sistolica, es. 120) misura la pressione nelle arterie nel momento in cui il cuore si contrae e pompa sangue nel sistema circolatorio — il picco massimo di pressione. Il secondo numero (pressione diastolica, es. 80) misura la pressione quando il cuore è rilassato tra un battito e l'altro, il valore minimo del ciclo. Entrambi i valori sono clinicamente rilevanti: una sistolica alta indica quanto sforzo il cuore deve fare per pompare sangue, mentre una diastolica alta indica una resistenza vascolare elevata anche a riposo, entrambi fattori di rischio cardiovascolare se cronicamente elevati (ipertensione), generalmente definita clinicamente come valori sopra 140/90 mmHg in modo persistente.$$),

(NULL, 'Come funziona un buco nero supermassiccio al centro delle galassie?', 'Scienziato', '🧪', 'lungo', 2000, $$Osservazioni ed evidenze: la presenza di buchi neri supermassicci (con masse tra milioni e miliardi di masse solari) al centro di quasi tutte le galassie con bulge significativo è oggi confermata da molteplici linee di evidenza indipendenti, incluse le orbite stellari nel centro della Via Lattea (che hanno permesso di misurare direttamente la massa di Sagittarius A*, valse il Nobel per la Fisica 2020) e le immagini dirette dell'Event Horizon Telescope (2019 per M87*, 2022 per Sagittarius A*).

Origine e crescita: l'origine esatta dei buchi neri supermassicci resta un problema aperto della cosmologia. Le ipotesi principali includono la crescita graduale per accrescimento e fusioni ripetute a partire da buchi neri di massa stellare, oppure il collasso diretto di enormi nubi di gas primordiale in condizioni particolari nell'universo primordiale, un percorso che potrebbe spiegare meglio l'esistenza di buchi neri supermassicci osservati già a redshift molto elevati (universo molto giovane), quando il tempo disponibile per una crescita graduale sarebbe stato insufficiente.

Relazione con la galassia ospite: esiste una correlazione notevole (relazione M-sigma) tra la massa del buco nero centrale e la dispersione di velocità delle stelle nel bulge galattico, suggerendo una co-evoluzione stretta tra il buco nero e la galassia stessa, probabilmente mediata da meccanismi di feedback energetico (getti relativistici, venti) che il buco nero attivo emette verso l'esterno, regolando la formazione stellare nella galassia ospite.

Limiti attuali della ricerca: la fisica esatta dei processi di accrescimento vicino all'orizzonte degli eventi, il meccanismo preciso di formazione dei getti relativistici, e il ruolo quantitativo del feedback nella regolazione dell'evoluzione galattica restano aree di ricerca attiva, con modelli teorici e simulazioni numeriche che convergono solo parzialmente con le osservazioni disponibili.$$),

(NULL, 'Perché i cani scodinzolano?', 'Bambino', '🧒', 'breve', 380, $$Scodinzolare è un modo che i cani hanno per esprimere quello che provano, un po' come noi sorridiamo o facciamo altre facce diverse. Scodinzolare in genere significa che il cane è contento o eccitato, ma non sempre allo stesso modo: se la coda si muove veloce e larga di solito il cane è felice, mentre se si muove più bassa e lenta potrebbe essere nervoso o incerto. Anche la direzione conta: gli scienziati hanno scoperto che i cani tendono a scodinzolare leggermente più verso destra quando provano emozioni positive, e più verso sinistra quando sono a disagio.$$),

(NULL, 'Come funziona l''assicurazione sulla vita?', 'Adulto', '👤', 'medio', 850, $$Un'assicurazione sulla vita è un contratto in cui paghi periodicamente un premio a una compagnia assicurativa, in cambio della quale i tuoi beneficiari (indicati da te nella polizza) ricevono una somma di denaro concordata se tu muori durante la durata del contratto. Esistono principalmente due tipologie: le polizze "caso morte" temporanee (term life), più economiche, che pagano solo se il decesso avviene entro un periodo definito (es. 20 anni) e non accumulano alcun valore se sopravvivi al termine; e le polizze "vita intera" o miste, più costose, che restano attive per tutta la vita e possono accumulare un valore di riscatto nel tempo, funzionando in parte anche come strumento di risparmio. La scelta dipende dall'obiettivo: proteggere economicamente la famiglia in caso di morte prematura (term life, più efficiente per questo scopo specifico) oppure combinare protezione e accumulo di capitale nel lungo periodo.$$);
