-- Batch 7: chiusura ampliamento community spiegazioni.

INSERT INTO public.spiegazioni (user_id, query, target_label, target_icon, length_key, response_chars, response_text) VALUES

(NULL, 'Perché quando fissiamo un colore a lungo e poi guardiamo altrove vediamo un colore "fantasma"?', 'Universitario', '🎓', 'medio', 1000, $$Questo fenomeno si chiama immagine residua negativa (afterimage) ed è dovuto all'affaticamento selettivo dei fotorecettori retinici. I coni della retina sono sensibili a tre colori base (rosso, verde, blu); fissando a lungo un colore intenso, i coni corrispondenti si "affaticano" e riducono temporaneamente la loro sensibilità per adattamento, mentre i coni delle altre tonalità restano a piena sensibilità. Quando sposti lo sguardo su una superficie neutra (come un muro bianco), il cervello riceve un segnale sbilanciato — i coni affaticati rispondono meno, quelli riposati rispondono normalmente — che viene interpretato come la percezione del colore complementare a quello originariamente fissato. L'effetto svanisce gradualmente man mano che i fotorecettori affaticati recuperano la loro sensibilità normale, di solito entro pochi secondi o minuti.$$),

(NULL, 'Come funziona il debito pubblico di un paese?', 'Adulto', '👤', 'medio', 900, $$Il debito pubblico è la somma totale che uno Stato deve ai suoi creditori (cittadini, banche, altri Stati, investitori internazionali) a causa di anni di bilanci in disavanzo, cioè spese superiori alle entrate fiscali. Lo Stato si finanzia principalmente emettendo titoli di debito (in Italia i BTP, BOT, CCT) che gli investitori acquistano in cambio di un interesse periodico; il debito pubblico non è quindi "denaro perso" ma un prestito che va restituito con gli interessi. Un debito elevato in rapporto al PIL (in Italia storicamente sopra il 130-150%) preoccupa perché aumenta la vulnerabilità del paese a shock economici (tassi di interesse più alti da pagare, minore margine per nuove spese in caso di crisi) e può erodere la fiducia dei mercati, con il rischio di un circolo vizioso in cui tassi più alti rendono il debito ancora più costoso da rifinanziare.$$),

(NULL, 'Perché alcuni animali vanno in letargo e altri no?', 'Ragazzo', '👨', 'medio', 800, $$Il letargo è una strategia di sopravvivenza che alcuni animali (come orsi, marmotte, ricci) usano per superare periodi in cui il cibo scarseggia drasticamente, tipicamente l'inverno. Durante il letargo, il metabolismo rallenta drasticamente: la temperatura corporea scende, il battito cardiaco e la respirazione si riducono enormemente, permettendo all'animale di consumare pochissima energia per mesi, vivendo delle riserve di grasso accumulate in autunno. Non tutti gli animali possono permetterselo: dipende dalla loro fisiologia (alcuni non riescono a tollerare cali di temperatura corporea così drastici senza danni), dalla loro dieta (i carnivori attivi tutto l'anno spesso trovano comunque prede anche d'inverno) e dalle strategie alternative disponibili, come la migrazione verso climi più caldi (praticata invece da molti uccelli) o semplicemente l'adattamento a trovare cibo anche nei mesi freddi.$$),

(NULL, 'Come funziona il sistema di allerta meteo (allerta arancione, rossa)?', 'Adulto', '👤', 'breve', 700, $$In Italia il sistema di allerta meteo, gestito dal Dipartimento della Protezione Civile insieme alle Regioni, usa un codice a colori per comunicare rapidamente il livello di rischio atteso per un territorio: verde (nessuna criticità particolare), gialla (criticità ordinaria, richiede solo attenzione), arancione (criticità moderata, possibili danni e disagi significativi) e rossa (criticità elevata, rischio per l'incolumità delle persone). Le allerte vengono emesse sulla base di previsioni meteorologiche e modelli idrogeologici che stimano probabilità di eventi come alluvioni, frane o temporali violenti, e determinano l'attivazione di specifici piani comunali di protezione civile (come la chiusura di scuole o l'evacuazione preventiva di aree a rischio), non sono quindi un semplice bollettino meteo ma un vero e proprio strumento operativo di gestione del rischio.$$),

(NULL, 'Perché la Nutella non si trova nella stessa ricetta esatta in tutti i paesi?', 'Ragazzo', '👨', 'breve', 600, $$La Ferrero adatta leggermente la ricetta della Nutella in base al mercato locale, principalmente per rispondere a normative alimentari diverse da paese a paese (ad esempio limiti diversi su zucchero, oli specifici ammessi, o requisiti di etichettatura) e per adattarsi alle preferenze di gusto regionali documentate tramite test di mercato. Le differenze non sono enormi ma sono reali e misurabili: alcuni consumatori segnalano, ad esempio, che la versione venduta negli Stati Uniti ha un sapore leggermente diverso da quella europea, principalmente per differenze nella miscela di oli vegetali utilizzata. La ricetta di base (nocciole, cacao, zucchero, olio di palma o alternative, latte scremato in polvere) resta comunque sostanzialmente la stessa a livello globale.$$),

(NULL, 'Come funziona il copyright su un''opera creativa?', 'Universitario', '🎓', 'medio', 1100, $$Il diritto d'autore (copyright) tutela automaticamente un'opera creativa originale (testo, musica, immagine, software) dal momento stesso della sua creazione, senza necessità di registrazione formale in molti ordinamenti (inclusa l'Italia, grazie alla Convenzione di Berna del 1886, adottata da quasi tutti i paesi del mondo). Il diritto d'autore si divide in due componenti: i diritti morali (paternità dell'opera, integrità), che sono in genere inalienabili e permanenti, e i diritti patrimoniali (sfruttamento economico: riproduzione, distribuzione, adattamento), che possono essere ceduti o concessi in licenza a terzi e hanno una durata limitata nel tempo — tipicamente la vita dell'autore più 70 anni nella maggior parte delle giurisdizioni, dopo i quali l'opera entra nel pubblico dominio e può essere liberamente utilizzata da chiunque.$$),

(NULL, 'Perché le patate diventano verdi se lasciate alla luce e perché non vanno mangiate così?', 'Bambino', '🧒', 'breve', 380, $$Quando le patate prendono troppa luce, iniziano a produrre clorofilla (la stessa sostanza verde delle foglie) come reazione naturale, un po' come se pensassero di dover iniziare a "fare la fotosintesi" come una pianta vera e propria. Insieme alla clorofilla, però, la patata produce anche una sostanza chiamata solanina, che serve a proteggerla ma che per noi è leggermente tossica se mangiata in grandi quantità. Per questo le parti verdi delle patate vanno sempre tagliate via prima di cucinarle, anche se il resto della patata è perfettamente sicuro da mangiare.$$),

(NULL, 'Come mai i tatuaggi restano per sempre sulla pelle?', 'Ragazzo', '👨', 'medio', 750, $$Quando ti tatui, l'ago inietta l'inchiostro in profondità, oltre l'epidermide (lo strato superficiale della pelle che si rinnova continuamente e si sfalda naturalmente ogni poche settimane) fino al derma, uno strato più profondo e stabile. Il corpo reagisce all'inchiostro come a un corpo estraneo, inviando cellule del sistema immunitario (macrofagi) per "ripulire" la zona: alcuni di questi macrofagi inglobano le particelle di inchiostro ma, non riuscendo a smaltirle completamente, restano intrappolati nel derma insieme al pigmento stesso, fissandolo in modo relativamente permanente. Con gli anni il tatuaggio può comunque sbiadire leggermente, perché una minima parte dell'inchiostro migra lentamente verso i linfonodi o perché le cellule contenenti il pigmento vengono gradualmente sostituite.$$),

(NULL, 'Perché il fuso orario cambia quando si attraversa la linea internazionale del cambiamento di data?', 'Esperto', '🧠', 'medio', 1000, $$La linea internazionale del cambiamento di data, che corre approssimativamente lungo il meridiano 180° nell'Oceano Pacifico (con deviazioni per non spezzare arbitrariamente territori nazionali), esiste per risolvere un problema logico intrinseco al sistema dei fusi orari: viaggiando verso est si guadagnano progressivamente ore rispetto al punto di partenza, viaggiando verso ovest se ne perdono, e senza un punto di "reset" queste differenze si accumulerebbero indefinitamente in un giro completo del globo, creando un'ambiguità di un giorno intero tra due punti geograficamente adiacenti. Attraversando la linea da ovest verso est si sottrae un giorno intero al calendario, mentre attraversandola da est verso ovest se ne aggiunge uno — una convenzione arbitraria ma necessaria per mantenere coerente il sistema globale dei fusi orari, stabilita informalmente nel XIX secolo con la standardizzazione internazionale dell'ora.$$),

(NULL, 'Perché a volte abbiamo la sensazione di "già vissuto" (déjà vu)?', 'Esperto', '🧠', 'medio', 1050, $$Il déjà vu non ha ancora una spiegazione scientifica definitiva e universalmente accettata, ma le teorie più accreditate riguardano piccole disfunzioni temporanee nei circuiti della memoria, in particolare nell'ippocampo e nelle aree temporali mediali del cervello. Un'ipotesi rilevante è quella del "riconoscimento familiare senza recupero della fonte": il cervello riconosce alcuni elementi di una scena nuova (una disposizione spaziale simile, un odore, un dettaglio visivo) come familiari, attivando il senso soggettivo di "già vissuto", senza però riuscire a recuperare la memoria specifica reale a cui quell'elemento si riferisce, creando quindi la sensazione paradossale di ricordare qualcosa di completamente nuovo. Studi con pazienti epilettici, in cui la stimolazione elettrica diretta di specifiche aree temporali del cervello può indurre artificialmente la sensazione di déjà vu, hanno fornito importanti indizi neurofisiologici a supporto di questa ipotesi.$$);
